"""
Karuwaki Speaks · Comprehensive Odia & Indic Cultural Lexicon
Provides authentic phonetic pronunciation transcriptions, natural prosody rules,
and text preprocessing for Indian English neural TTS (en-IN-NeerjaNeural / en-IN-NeerjaExpressiveNeural).
Contains over 1,000 carefully mapped Odia cultural, sacred, traditional and linguistic expressions.
"""

import re
from html import unescape
from django.utils.html import strip_tags

# Comprehensive Odia & Indic Phonetic Dictionary
# Maps transliterated cultural terms to natural phonetic guides for en-IN neural TTS
ODIA_PHONETIC_LEXICON = {
    r"\bOdia\ Language\ Classical\ Status\b": "Oh-dee-aa Language Classical Status",
    r"\bAndha\ Deshe\ Gala\ Darpana\ Biki\b": "Un-dhaa Day-shay Guh-laa Dur-puh-nuh Bee-kee",
    r"\bKishora\ Chandrananda\ Champu\b": "Kee-shohr Chun-dhruh-nun-duh Chhum-poo",
    r"\bTwelve\ Hundred\ Stonemasons\b": "Twelve Hundred Stonemasons",
    r"\bBritish\ Conquest\ of\ Odisha\b": "British Conquest of Oh-dee-shaa",
    r"\bMitha\ Kathare\ Manisa\ Bashe\b": "Mee-thaa Kuh-thaa-ray Muh-nee-suh Buh-shay",
    r"\bUdhura\ Pinda\ Kudhura\ Khai\b": "Oo-dhoo-ruh Pin-duh Koo-dhoo-ruh Khye",
    r"\bKete\ Ghadake\ Kete\ Taranga\b": "Kay-tay Ghuh-duh-kay Kay-tay Tuh-rung-guh",
    r"\bPralambasura\ Badha\ Besha\b": "Pruh-lum-baa-soo-ruh Buh-dhuh Bay-shuh",
    r"\bParalakhemundi\ Horn\ Work\b": "Paa-ruh-laa-khem-oon-dee Horn Work",
    r"\bMahapurusha\ Achyutananda\b": "Muh-haa-poo-roo-shuh Uh-chyoo-taa-nun-duh",
    r"\bGopalakrushna\ Pattanayak\b": "Goh-paa-luh-krush-nuh Put-tuh-naa-yuck",
    r"\bKalindi\ Charan\ Panigrahi\b": "Kaa-lin-dee Chuh-run Paa-nee-graa-hee",
    r"\bJashya\ Balam\ Tasya\ Balam\b": "Jush-yuh Buh-lum Tus-yuh Buh-lum",
    r"\bHathigumpha\ Inscription\b": "Haa-thee-goom-faa Inscription",
    r"\bMayadhar\ Mansingh\ Kavya\b": "Mye-aa-dhur Muan-singh Kaav-yuh",
    r"\bKshetra\ Budhi\ Thakurani\b": "Kshetra Boo-dhee Thaa-koo-raa-nee",
    r"\bBipade\ Bandhu\ Parikshya\b": "Bih-puh-day Bun-dhoo Puh-reek-shyuh",
    r"\bGhatagaon\ Tarini\ Pitha\b": "Ghuh-tuh-gaanw Taa-rih-nee Pee-thuh",
    r"\bKrushna\ Balarama\ Besha\b": "Krush-nuh Buh-luh-raam Bay-shuh",
    r"\bMaha\ Bishuva\ Sankranti\b": "Muh-haa Bih-shoo-vuh Sung-kraan-tee",
    r"\bLangula\ Narasimha\ Deva\b": "Laang-goo-laa Nuh-ruh-sing-huh Day-vuh",
    r"\bMaratha\ Rule\ in\ Odisha\b": "Muh-raa-thaa Rule in Oh-dee-shaa",
    r"\bPremabhakti\ Brahmagita\b": "Pray-muh-bhuk-tee Bruh-muh-gee-taa",
    r"\bMandir\ Budhi\ Thakurani\b": "Mandir Boo-dhee Thaa-koo-raa-nee",
    r"\bTemple\ Budhi\ Thakurani\b": "Temple Boo-dhee Thaa-koo-raa-nee",
    r"\bNimapada\ Chhena\ Jhili\b": "Nee-muh-puh-daa Chhay-naa Jhee-lee",
    r"\bNabakrushna\ Choudhury\b": "Nuh-buh-krush-nuh Chow-dhoo-ree",
    r"\bKotibrahmanda\ Sundari\b": "Koh-tih-bruhm-aan-duh Soon-duh-ree",
    r"\bChha\ Mana\ Atha\ Guntha\b": "Chhaa Maa-nuh Aath Goon-thuh",
    r"\bShree\ Budhi\ Thakurani\b": "Shree Boo-dhee Thaa-koo-raa-nee",
    r"\bKshetra\ Akhandalamani\b": "Kshetra Uh-khun-duh-luh-muh-nee",
    r"\bKshetra\ Nrusinghanath\b": "Kshetra Nroo-sing-huh-naath",
    r"\bKshetra\ Majhighariani\b": "Kshetra Maa-jee-ghuh-ree-yaa-nee",
    r"\bPitha\ Budhi\ Thakurani\b": "Pitha Boo-dhee Thaa-koo-raa-nee",
    r"\bBaba\ Panchalingeswar\b": "Baa-baa Pun-chuh-ling-gesh-wurr",
    r"\bGaja\ Uddharana\ Besha\b": "Guh-juh Ood-dhaa-ruh-nuh Bay-shuh",
    r"\bRadha\ Damodara\ Besha\b": "Raa-dhaa Daa-moh-duh-ruh Bay-shuh",
    r"\bIndradyumna\ Sarovara\b": "In-druh-dyoom-nuh Suh-roh-vuh-ruh",
    r"\bNayagarh\ Chhena\ Poda\b": "Nye-uh-gud Chhay-naa Paw-duh",
    r"\bGita\ Govinda\ Khandua\b": "Gee-tuh Goh-vin-duh Khun-doo-aa",
    r"\bKelucharan\ Mohapatra\b": "Kay-loo-chuh-run Moh-huh-paa-truh",
    r"\bUtkalmani\ Gopabandhu\b": "Oot-kuhl-muh-nee Goh-puh-bun-dhoo",
    r"\bFakir\ Mohan\ Senapati\b": "Fuh-keer Moh-hun Say-naa-puh-tee",
    r"\bSachidananda\ Routray\b": "Suh-chih-daa-nun-duh Rowt-rye",
    r"\bKuntala\ Kumari\ Sabat\b": "Koon-tuh-laa Koo-maa-ree Suh-but",
    r"\bKonark\ Temple\ Legend\b": "Koh-naark Temple Legend",
    r"\bHetu\ Udaya\ Bhagavata\b": "Hay-too Oo-duh-yuh Bhaa-guh-vuh-tuh",
    r"\bKantakabi\ Laxmikanta\b": "Kaan-tuh-kuh-bee Lux-mee-kaan-tuh",
    r"\bLaxmikanta\ Mohapatra\b": "Lux-mee-kaan-tuh Moh-huh-paa-truh",
    r"\bLord\ Budhi\ Thakurani\b": "Lord Boo-dhee Thaa-koo-raa-nee",
    r"\bBaba\ Budhi\ Thakurani\b": "Baba Boo-dhee Thaa-koo-raa-nee",
    r"\bDevi\ Budhi\ Thakurani\b": "Devi Boo-dhee Thaa-koo-raa-nee",
    r"\bMandir\ Akhandalamani\b": "Mandir Uh-khun-duh-luh-muh-nee",
    r"\bMandir\ Nrusinghanath\b": "Mandir Nroo-sing-huh-naath",
    r"\bMandir\ Majhighariani\b": "Mandir Maa-jee-ghuh-ree-yaa-nee",
    r"\bTemple\ Akhandalamani\b": "Temple Uh-khun-duh-luh-muh-nee",
    r"\bTemple\ Nrusinghanath\b": "Temple Nroo-sing-huh-naath",
    r"\bTemple\ Majhighariani\b": "Temple Maa-jee-ghuh-ree-yaa-nee",
    r"\bKshetra\ Khambeshwari\b": "Kshetra Khum-besh-wuh-ree",
    r"\bGhara\ Dinki\ Kumbhira\b": "Ghuh-ruh Deeng-kee Koom-bhee-ruh",
    r"\bKatha\ Re\ Katha\ Badhe\b": "Kuh-thaa Ray Kuh-thaa Buh-dhay",
    r"\bKhirachora\ Gopinath\b": "Khee-ruh-choh-raa Goh-pee-naath",
    r"\bPanchamukhi\ Hanuman\b": "Pun-chuh-moo-khee Huh-noo-maan",
    r"\bMarkandeya\ Sarovara\b": "Maar-kun-day-yuh Suh-roh-vuh-ruh",
    r"\bNarendra\ Pushkarini\b": "Nuh-ren-dhruh Poosh-kuh-ree-nee",
    r"\bBargarh\ Dhanu\ Jatra\b": "Bur-gud Dhuh-noo Jaah-traa",
    r"\bChaitra\ Mangalabara\b": "Chye-truh Mung-guh-luh-baa-ruh",
    r"\bKendrapara\ Rasabali\b": "Ken-drah-puh-raa Ruh-suh-buh-lee",
    r"\bRaghunath\ Panigrahi\b": "Ruh-ghoo-naath Paa-nee-graa-hee",
    r"\bBhubaneswari\ Mishra\b": "Bhoo-buh-nesh-wuh-ree Mish-ruh",
    r"\bTribhuvana\ Mahadevi\b": "Tree-bhoo-vuh-nuh Muh-haa-day-vee",
    r"\bSuryavamsi\ Gajapati\b": "Soor-yuh-vum-shee Guh-juh-puh-tee",
    r"\bHarekrushna\ Mahatab\b": "Huh-ray-krush-nuh Muh-haa-taab",
    r"\bStatehood\ of\ Odisha\b": "Statehood of Oh-dee-shaa",
    r"\bJagamohana\ Ramayana\b": "Juh-guh-moh-hun Raa-maa-yuh-nuh",
    r"\bGovindachandra\ Tika\b": "Goh-vin-duh-chun-dhruh Tee-kaa",
    r"\bBande\ Utkala\ Janani\b": "Bun-day Oot-kuhl Juh-nuh-nee",
    r"\bMaa\ Budhi\ Thakurani\b": "Maa Boo-dhee Thaa-koo-raa-nee",
    r"\bShree\ Akhandalamani\b": "Shree Uh-khun-duh-luh-muh-nee",
    r"\bShree\ Nrusinghanath\b": "Shree Nroo-sing-huh-naath",
    r"\bShree\ Majhighariani\b": "Shree Maa-jee-ghuh-ree-yaa-nee",
    r"\bSri\ Budhi\ Thakurani\b": "Sri Boo-dhee Thaa-koo-raa-nee",
    r"\bMandir\ Khambeshwari\b": "Mandir Khum-besh-wuh-ree",
    r"\bTemple\ Khambeshwari\b": "Temple Khum-besh-wuh-ree",
    r"\bKshetra\ Samaleswari\b": "Kshetra Suh-muhl-esh-wuh-ree",
    r"\bKshetra\ Dhabaleswar\b": "Kshetra Dhuh-buhl-esh-wurr",
    r"\bKshetra\ Harishankar\b": "Kshetra Huh-ree-shun-kurr",
    r"\bKshetra\ Nilamadhaba\b": "Kshetra Neel-uh-maadh-uh-vuh",
    r"\bPitha\ Akhandalamani\b": "Pitha Uh-khun-duh-luh-muh-nee",
    r"\bPitha\ Nrusinghanath\b": "Pitha Nroo-sing-huh-naath",
    r"\bPitha\ Majhighariani\b": "Pitha Maa-jee-ghuh-ree-yaa-nee",
    r"\bBaba\ Akhandalamani\b": "Baa-baa Uh-khun-duh-luh-muh-nee",
    r"\bSixty\ Four\ Yoginis\b": "Sixty Four Yoh-gih-nees",
    r"\bBarala\ Balunkeswar\b": "Baa-ruh-laa Buh-loon-kesh-wurr",
    r"\bBada\ Singhar\ Besha\b": "Buh-duh Sing-haar Bay-shuh",
    r"\bBada\ Singhar\ Bhoga\b": "Buh-duh Sing-haar Bhohg",
    r"\bChitalagi\ Amavasya\b": "Chih-tuh-laa-gee Uh-maa-vus-yaa",
    r"\bDahi\ Bara\ Aloo\ Dum\b": "Duh-hee Buh-raa Aa-loo Doom",
    r"\bSanjukta\ Panigrahi\b": "Sun-jook-tuh Paa-nee-graa-hee",
    r"\bBhubaneswar\ Mishra\b": "Bhoo-buh-nesh-wurr Mish-ruh",
    r"\bRemuna\ Pattachitra\b": "Ray-moo-naa Put-tuh-chih-truh",
    r"\bKabibara\ Radhanath\b": "Kuh-bee-buh-ruh Raa-dhaa-naath",
    r"\bSitakant\ Mahapatra\b": "See-tuh-kaant Moh-huh-paa-truh",
    r"\bGodabarisha\ Mishra\b": "Goh-daa-buh-ree-shuh Mish-ruh",
    r"\bNa\ Anka\ Durbhikhya\b": "Nuh Ung-kuh Door-bheek-shyuh",
    r"\bOrissa\ Famine\ 1866\b": "Oh-dih-shaa Famine 1866",
    r"\bSarala\ Mahabharata\b": "Saa-ruh-laa Muh-haa-bhaa-rut",
    r"\bAtibadi\ Jagannatha\b": "Uh-tih-buh-dee Juh-gun-naath",
    r"\bAnnada\ Shankar\ Ray\b": "Aa-nun-duh Shun-kur Rye",
    r"\bChintamani\ Mohanty\b": "Chin-taa-muh-nee Moh-hun-tee",
    r"\bRadharaman\ Panjika\b": "Raa-dhaa-ruh-mun Pun-jee-kaa",
    r"\bLord\ Akhandalamani\b": "Lord Uh-khun-duh-luh-muh-nee",
    r"\bLord\ Nrusinghanath\b": "Lord Nroo-sing-huh-naath",
    r"\bLord\ Majhighariani\b": "Lord Maa-jee-ghuh-ree-yaa-nee",
    r"\bBaba\ Nrusinghanath\b": "Baba Nroo-sing-huh-naath",
    r"\bBaba\ Majhighariani\b": "Baba Maa-jee-ghuh-ree-yaa-nee",
    r"\bShree\ Khambeshwari\b": "Shree Khum-besh-wuh-ree",
    r"\bDevi\ Akhandalamani\b": "Devi Uh-khun-duh-luh-muh-nee",
    r"\bDevi\ Nrusinghanath\b": "Devi Nroo-sing-huh-naath",
    r"\bDevi\ Majhighariani\b": "Devi Maa-jee-ghuh-ree-yaa-nee",
    r"\bMandir\ Samaleswari\b": "Mandir Suh-muhl-esh-wuh-ree",
    r"\bMandir\ Dhabaleswar\b": "Mandir Dhuh-buhl-esh-wurr",
    r"\bMandir\ Harishankar\b": "Mandir Huh-ree-shun-kurr",
    r"\bMandir\ Nilamadhaba\b": "Mandir Neel-uh-maadh-uh-vuh",
    r"\bTemple\ Samaleswari\b": "Temple Suh-muhl-esh-wuh-ree",
    r"\bTemple\ Dhabaleswar\b": "Temple Dhuh-buhl-esh-wurr",
    r"\bTemple\ Harishankar\b": "Temple Huh-ree-shun-kurr",
    r"\bTemple\ Nilamadhaba\b": "Temple Neel-uh-maadh-uh-vuh",
    r"\bKshetra\ Balabhadra\b": "Kshetra Buhl-uh-bhuh-druh",
    r"\bKshetra\ Bhattarika\b": "Kshetra Bhut-taa-rih-kaa",
    r"\bKshetra\ Taratarini\b": "Kshetra Taa-raa Taa-rih-nee",
    r"\bPitha\ Khambeshwari\b": "Pitha Khum-besh-wuh-ree",
    r"\bMaa\ Majhighariani\b": "Maa Maa-jee-ghuh-ree-yaa-nee",
    r"\bGajapati\ Maharaja\b": "Guh-juh-puh-tee Muh-haa-raa-jaa",
    r"\bKaliyadalan\ Besha\b": "Kaa-lee-yuh-duh-lun Bay-shuh",
    r"\bPatitapabana\ Bana\b": "Puh-tih-tuh-paa-buh-nuh Buh-naa",
    r"\bMeghanada\ Pacheri\b": "May-ghuh-naa-duh Puh-chay-ree",
    r"\bNarendra\ Sarovara\b": "Nuh-ren-dhruh Suh-roh-vuh-ruh",
    r"\bMargasira\ Gurubar\b": "Muur-guh-shee-ruh Goo-roo-baar",
    r"\bChandrabhaga\ Mela\b": "Chun-dhruh-bhaa-gaa May-laa",
    r"\bMaa\ Mangala\ Yatra\b": "Maa Mung-guh-laa Yaah-traa",
    r"\bCuttack\ Dahi\ Bara\b": "Kuh-tuck Duh-hee Buh-raa",
    r"\bSambalpuri\ Nrutya\b": "Sum-buhl-poo-ree Nroot-yuh",
    r"\bSudarsan\ Pattnaik\b": "Soo-dur-shun Put-naa-yick",
    r"\bPankaj\ Charan\ Das\b": "Pung-kuj Chuh-run Daas",
    r"\bPrincess\ Karuwaki\b": "Princess Kah-roo-vah-kee",
    r"\bPurushottama\ Deva\b": "Poo-roo-shoht-tuh-muh Day-vuh",
    r"\bVeer\ Surendra\ Sai\b": "Veer Soo-ren-dhruh Saa-ee",
    r"\bDharanidhar\ Nayak\b": "Dhuh-ruh-nee-dhur Naa-yuck",
    r"\bPandit\ Gopabandhu\b": "Pun-dit Goh-puh-bun-dhoo",
    r"\bJayanta\ Mahapatra\b": "Juh-yun-tuh Moh-huh-paa-truh",
    r"\bMayadhar\ Mansingh\b": "Mye-aa-dhur Muan-singh",
    r"\bAchyutananda\ Dasa\b": "Uh-chyoo-taa-nun-duh Daas",
    r"\bBaidehisha\ Vilasa\b": "Bye-day-hee-shuh Vih-laa-suh",
    r"\bAtithi\ Devo\ Bhava\b": "Uh-tee-thee Day-voh Bhuh-vuh",
    r"\bLord\ Khambeshwari\b": "Lord Khum-besh-wuh-ree",
    r"\bMaa\ Akhandalamani\b": "Maa Uh-khun-duh-luh-muh-nee",
    r"\bMaa\ Nrusinghanath\b": "Maa Nroo-sing-huh-naath",
    r"\bBaba\ Khambeshwari\b": "Baba Khum-besh-wuh-ree",
    r"\bShree\ Samaleswari\b": "Shree Suh-muhl-esh-wuh-ree",
    r"\bShree\ Dhabaleswar\b": "Shree Dhuh-buhl-esh-wurr",
    r"\bShree\ Harishankar\b": "Shree Huh-ree-shun-kurr",
    r"\bShree\ Nilamadhaba\b": "Shree Neel-uh-maadh-uh-vuh",
    r"\bSri\ Akhandalamani\b": "Sri Uh-khun-duh-luh-muh-nee",
    r"\bSri\ Nrusinghanath\b": "Sri Nroo-sing-huh-naath",
    r"\bSri\ Majhighariani\b": "Sri Maa-jee-ghuh-ree-yaa-nee",
    r"\bDevi\ Khambeshwari\b": "Devi Khum-besh-wuh-ree",
    r"\bMandir\ Balabhadra\b": "Mandir Buhl-uh-bhuh-druh",
    r"\bMandir\ Bhattarika\b": "Mandir Bhut-taa-rih-kaa",
    r"\bMandir\ Taratarini\b": "Mandir Taa-raa Taa-rih-nee",
    r"\bTemple\ Balabhadra\b": "Temple Buhl-uh-bhuh-druh",
    r"\bTemple\ Bhattarika\b": "Temple Bhut-taa-rih-kaa",
    r"\bTemple\ Taratarini\b": "Temple Taa-raa Taa-rih-nee",
    r"\bKshetra\ Jagannath\b": "Kshetra Jug-un-naath",
    r"\bKshetra\ Gupteswar\b": "Kshetra Goop-tesh-wurr",
    r"\bKshetra\ Charchika\b": "Kshetra Chur-chih-kaa",
    r"\bPitha\ Samaleswari\b": "Pitha Suh-muhl-esh-wuh-ree",
    r"\bPitha\ Dhabaleswar\b": "Pitha Dhuh-buhl-esh-wurr",
    r"\bPitha\ Harishankar\b": "Pitha Huh-ree-shun-kurr",
    r"\bPitha\ Nilamadhaba\b": "Pitha Neel-uh-maadh-uh-vuh",
    r"\bChakra\ Sudarshan\b": "Chuk-ruh Soo-dur-shun",
    r"\bKakatpur\ Mangala\b": "Kaa-kut-poor Mung-guh-laa",
    r"\bGhatagaon\ Tarini\b": "Ghuh-tuh-gaanw Taa-rih-nee",
    r"\bBaba\ Dhabaleswar\b": "Baa-baa Dhuh-buhl-esh-wurr",
    r"\bBiranchi\ Narayan\b": "Bih-run-chee Nuh-raa-yun",
    r"\bChausathi\ Yogini\b": "Chow-suth-ee Yoh-gih-nee",
    r"\bMaa\ Manikeshwari\b": "Maa Maa-nih-kesh-wuh-ree",
    r"\bMaa\ Dakshinakali\b": "Maa Duk-shih-nuh Kaa-lee",
    r"\bTribikrama\ Besha\b": "Trih-bih-kruh-muh Bay-shuh",
    r"\bRadhakanta\ Matha\b": "Raa-dhaa-kaan-tuh Muth",
    r"\bRaghav\ Das\ Matha\b": "Raa-ghuv Daas Muth",
    r"\bJagannath\ Ballav\b": "Jug-un-naath Buh-luhv",
    r"\bSwargadwara\ Puri\b": "Swur-guh-dwaa-ruh Poo-ree",
    r"\bManabasa\ Gurubar\b": "Maa-nuh-buh-saa Goo-roo-baar",
    r"\bOdia\ Naba\ Barsha\b": "Oh-dee-aa Nuh-buh Bur-shuh",
    r"\bKhudurukuni\ Osha\b": "Khoo-doo-roo-koo-nee Oh-shaa",
    r"\bTriveni\ Amavasya\b": "Trih-vay-nee Uh-maa-vus-yaa",
    r"\bMachha\ Chencheda\b": "Maach-uh Chen-chay-daa",
    r"\bSalepur\ Rasagola\b": "Saa-lay-poor Ruh-suh-goh-laa",
    r"\bMayurbhanj\ Chhau\b": "Maa-yoor-bhunj Chhow",
    r"\bTalapatra\ Chitra\b": "Taa-luh-puh-truh Chih-truh",
    r"\bCuttack\ Tarakasi\b": "Kuh-tuck Taa-raa-kuh-see",
    r"\bBaleswar\ Lacquer\b": "Buhl-esh-wurr Luh-kur",
    r"\bSambalpuri\ Saree\b": "Sum-buhl-poo-ree Saa-ree",
    r"\bBerhampuri\ Patta\b": "Behr-hum-poo-ree Put-tuh",
    r"\bBalakrushna\ Dash\b": "Buhl-uh-krush-nuh Daash",
    r"\bBargaon\ Handloom\b": "Bur-gaanw Handloom",
    r"\bRamachandi\ Beach\b": "Raa-muh-chun-dee Beach",
    r"\bPrithvi\ Mahadevi\b": "Prith-vee Muh-haa-day-vee",
    r"\bGajapati\ Dynasty\b": "Guh-juh-puh-tee Dynasty",
    r"\bPrataprudra\ Deva\b": "Pruh-taap-roo-dhruh Day-vuh",
    r"\bRamachandra\ Deva\b": "Raa-muh-chun-dhruh Day-vuh",
    r"\bMalati\ Choudhury\b": "Maa-luh-tee Chow-dhoo-ree",
    r"\bNandini\ Satpathy\b": "Nun-dih-nee Sut-puh-thee",
    r"\bGopinath\ Mohanty\b": "Goh-pee-naath Moh-hun-tee",
    r"\bSurendra\ Mohanty\b": "Soo-ren-dhruh Moh-hun-tee",
    r"\bVilanka\ Ramayana\b": "Bih-lung-kaa Raa-maa-yuh-nuh",
    r"\bStuti\ Chintamani\b": "Stoo-tee Chin-taa-muh-nee",
    r"\bKavita\ Kallolini\b": "Kuh-vih-taa Kuhl-loh-lee-nee",
    r"\bKohinoor\ Panjika\b": "Kohinoor Pun-jee-kaa",
    r"\bSambalpuri\ Juhar\b": "Sum-buhl-poo-ree Joo-haar",
    r"\bPuna\ Janmaku\ Gai\b": "Poo-nuh Jun-muh-koo Gye",
    r"\bKala\ O\ Sanskruti\b": "Kuh-laa Oh Sun-skroo-tee",
    r"\bLord\ Samaleswari\b": "Lord Suh-muhl-esh-wuh-ree",
    r"\bLord\ Dhabaleswar\b": "Lord Dhuh-buhl-esh-wurr",
    r"\bLord\ Harishankar\b": "Lord Huh-ree-shun-kurr",
    r"\bLord\ Nilamadhaba\b": "Lord Neel-uh-maadh-uh-vuh",
    r"\bMaa\ Khambeshwari\b": "Maa Khum-besh-wuh-ree",
    r"\bBaba\ Samaleswari\b": "Baba Suh-muhl-esh-wuh-ree",
    r"\bBaba\ Harishankar\b": "Baba Huh-ree-shun-kurr",
    r"\bBaba\ Nilamadhaba\b": "Baba Neel-uh-maadh-uh-vuh",
    r"\bShree\ Balabhadra\b": "Shree Buhl-uh-bhuh-druh",
    r"\bShree\ Bhattarika\b": "Shree Bhut-taa-rih-kaa",
    r"\bShree\ Taratarini\b": "Shree Taa-raa Taa-rih-nee",
    r"\bSri\ Khambeshwari\b": "Sri Khum-besh-wuh-ree",
    r"\bDevi\ Samaleswari\b": "Devi Suh-muhl-esh-wuh-ree",
    r"\bDevi\ Dhabaleswar\b": "Devi Dhuh-buhl-esh-wurr",
    r"\bDevi\ Harishankar\b": "Devi Huh-ree-shun-kurr",
    r"\bDevi\ Nilamadhaba\b": "Devi Neel-uh-maadh-uh-vuh",
    r"\bMandir\ Jagannath\b": "Mandir Jug-un-naath",
    r"\bMandir\ Gupteswar\b": "Mandir Goop-tesh-wurr",
    r"\bMandir\ Charchika\b": "Mandir Chur-chih-kaa",
    r"\bTemple\ Jagannath\b": "Temple Jug-un-naath",
    r"\bTemple\ Gupteswar\b": "Temple Goop-tesh-wurr",
    r"\bTemple\ Charchika\b": "Temple Chur-chih-kaa",
    r"\bKshetra\ Lingaraj\b": "Kshetra Ling-guh-raaj",
    r"\bKshetra\ Subhadra\b": "Kshetra Soo-bhuh-dhrah",
    r"\bKshetra\ Lokanath\b": "Kshetra Loh-kuh-naath",
    r"\bPitha\ Balabhadra\b": "Pitha Buhl-uh-bhuh-druh",
    r"\bPitha\ Bhattarika\b": "Pitha Bhut-taa-rih-kaa",
    r"\bPitha\ Taratarini\b": "Pitha Taa-raa Taa-rih-nee",
    r"\bHira\ Nila\ Manika\b": "Hee-raa Nee-laa Maa-nih-kuh",
    r"\bBudhi\ Thakurani\b": "Boo-dhee Thaa-koo-raa-nee",
    r"\bMaa\ Khambeswari\b": "Maa Khum-besh-wuh-ree",
    r"\bAnanta\ Vasudeva\b": "Uh-nun-tuh Vaa-soo-dhev",
    r"\bMaa\ Pataneswari\b": "Maa Puh-tuh-nesh-wuh-ree",
    r"\bMaa\ Ghanteswari\b": "Maa Ghun-tesh-wuh-ree",
    r"\bPanchalingeswar\b": "Pun-chuh-ling-gesh-wurr",
    r"\bNilakantheswara\b": "Nee-luh-kun-thesh-wuh-ruh",
    r"\bMaa\ Kanakadurga\b": "Maa Kuh-nuh-kuh-door-gaa",
    r"\bBanki\ Charchika\b": "Bung-kee Chur-chih-kaa",
    r"\bChhatisa\ Nijoga\b": "Chhuh-tee-saa Nih-joh-guh",
    r"\bMadhyanna\ Dhupa\b": "Mud-hyun-nuh Dhoo-puh",
    r"\bBanabhoji\ Besha\b": "Buh-nuh-bhoh-jee Bay-shuh",
    r"\bNagarjuna\ Besha\b": "Naa-gaar-joo-nuh Bay-shuh",
    r"\bSandhya\ Darshan\b": "Sun-dhyaa Dur-shun",
    r"\bBrahma\ Padartha\b": "Bruh-muh Puh-daar-thuh",
    r"\bKoili\ Vaikuntha\b": "Koy-lee Vye-koon-thuh",
    r"\bGundicha\ Mandir\b": "Goon-dih-chaa Mun-deer",
    r"\bBedha\ Parikrama\b": "Bay-dhaa Puh-ree-kruh-muh",
    r"\bKartika\ Purnima\b": "Kaar-tih-kuh Poor-nih-maa",
    r"\bMesha\ Sankranti\b": "May-shuh Sung-kraan-tee",
    r"\bKartika\ Somabar\b": "Kaar-tih-kuh Soh-muh-baar",
    r"\bMaha\ Shivaratri\b": "Muh-haa Shih-vuh-raat-ree",
    r"\bMakar\ Sankranti\b": "Muh-kur Sung-kraan-tee",
    r"\bKanji\ Anla\ Osha\b": "Kaan-jee Aam-laa Oh-shaa",
    r"\bKhandagiri\ Mela\b": "Khun-duh-gih-ree May-laa",
    r"\bBakula\ Amavasya\b": "Buh-koo-laa Uh-maa-vus-yaa",
    r"\bSubarnapur\ Mela\b": "Soo-bur-nuh-poor May-laa",
    r"\bAnna\ Mahaprasad\b": "Un-nuh Maa-haa-pruh-saadh",
    r"\bChaunka\ Pakhala\b": "Chown-kaa Puh-khaa-luh",
    r"\bChingudi\ Sukhua\b": "Ching-goo-dee Soo-khoo-aa",
    r"\bPahala\ Rasagola\b": "Puh-huh-laa Ruh-suh-goh-laa",
    r"\bBikalananda\ Kar\b": "Bih-kuh-laa-nun-duh Kur",
    r"\bAlu\ Potola\ Rasa\b": "Aa-loo Poh-tuh-luh Ruh-suh",
    r"\bPrahlada\ Nataka\b": "Pruh-hlaa-duh Naa-tuh-kuh",
    r"\bSilver\ Filigree\b": "Silver Fih-lih-gree",
    r"\bGuru\ Kelucharan\b": "Goo-roo Kay-loo-chuh-run",
    r"\bDeba\ Prasad\ Das\b": "Day-buh Pruh-saadh Daas",
    r"\bAkshaya\ Mohanty\b": "Uhk-shuh-yuh Moh-hun-tee",
    r"\bArabinda\ Muduli\b": "Uh-ruh-bin-duh Moo-doo-lee",
    r"\bGopalpur\ Tussar\b": "Goh-paal-poor Tuh-suhr",
    r"\bDakshina\ Kosala\b": "Duk-shih-nuh Koh-suh-luh",
    r"\bBhandaripokhari\b": "Bhun-daa-ree-poh-khuh-ree",
    r"\bMahameghavahana\b": "Maa-haa-may-ghuh-vaa-huh-nuh",
    r"\bChodaganga\ Deva\b": "Choh-duh-gung-guh Day-vuh",
    r"\bKapilendra\ Deva\b": "Kuh-pih-len-dhruh Day-vuh",
    r"\bBuxi\ Jagabandhu\b": "Book-shee Juh-guh-bun-dhoo",
    r"\bPaika\ Rebellion\b": "Pye-kuh Rebellion",
    r"\bGangadhar\ Meher\b": "Gung-gaa-dhur May-hur",
    r"\bAcharya\ Harihar\b": "Aa-chaar-yuh Huh-ree-hur",
    r"\bMathara\ Dynasty\b": "Maa-thuh-ruh Dynasty",
    r"\bUtkal\ Sammilani\b": "Oot-kuhl Sum-mee-luh-nee",
    r"\bJagannatha\ Dasa\b": "Juh-gun-naath Daas",
    r"\bBhagavata\ Tungi\b": "Bhaa-guh-vuh-tuh Toong-gee",
    r"\bBhabisya\ Malika\b": "Bhu-vihsh-yuh Maa-lih-kaa",
    r"\bPremasudhanidhi\b": "Pray-muh-soo-dhaa-nee-dhee",
    r"\bBhakta\ Salabega\b": "Bhuk-tuh Suh-luh-bay-guh",
    r"\bPranaya\ Ballari\b": "Pruh-nuh-yuh Buh-luh-ree",
    r"\bPinda\ Brahmanda\b": "Pin-duh Bruhm-aan-duh",
    r"\bOdia\ Barnabodha\b": "Oh-dee-aa Bur-nuh-boh-dhuh",
    r"\bAbhijit\ Muhurta\b": "Uh-bhee-jeet Moo-hoor-tuh",
    r"\bKemiti\ Achhanti\b": "Kay-mee-tee Aachh-un-tee",
    r"\bLord\ Balabhadra\b": "Lord Buhl-uh-bhuh-druh",
    r"\bLord\ Bhattarika\b": "Lord Bhut-taa-rih-kaa",
    r"\bLord\ Taratarini\b": "Lord Taa-raa Taa-rih-nee",
    r"\bMaa\ Samaleswari\b": "Maa Suh-muhl-esh-wuh-ree",
    r"\bMaa\ Dhabaleswar\b": "Maa Dhuh-buhl-esh-wurr",
    r"\bMaa\ Harishankar\b": "Maa Huh-ree-shun-kurr",
    r"\bMaa\ Nilamadhaba\b": "Maa Neel-uh-maadh-uh-vuh",
    r"\bBaba\ Balabhadra\b": "Baba Buhl-uh-bhuh-druh",
    r"\bBaba\ Bhattarika\b": "Baba Bhut-taa-rih-kaa",
    r"\bBaba\ Taratarini\b": "Baba Taa-raa Taa-rih-nee",
    r"\bShree\ Jagannath\b": "Shree Jug-un-naath",
    r"\bShree\ Gupteswar\b": "Shree Goop-tesh-wurr",
    r"\bShree\ Charchika\b": "Shree Chur-chih-kaa",
    r"\bSri\ Samaleswari\b": "Sri Suh-muhl-esh-wuh-ree",
    r"\bSri\ Dhabaleswar\b": "Sri Dhuh-buhl-esh-wurr",
    r"\bSri\ Harishankar\b": "Sri Huh-ree-shun-kurr",
    r"\bSri\ Nilamadhaba\b": "Sri Neel-uh-maadh-uh-vuh",
    r"\bDevi\ Balabhadra\b": "Devi Buhl-uh-bhuh-druh",
    r"\bDevi\ Bhattarika\b": "Devi Bhut-taa-rih-kaa",
    r"\bDevi\ Taratarini\b": "Devi Taa-raa Taa-rih-nee",
    r"\bMandir\ Lingaraj\b": "Mandir Ling-guh-raaj",
    r"\bMandir\ Subhadra\b": "Mandir Soo-bhuh-dhrah",
    r"\bMandir\ Lokanath\b": "Mandir Loh-kuh-naath",
    r"\bTemple\ Lingaraj\b": "Temple Ling-guh-raaj",
    r"\bTemple\ Subhadra\b": "Temple Soo-bhuh-dhrah",
    r"\bTemple\ Lokanath\b": "Temple Loh-kuh-naath",
    r"\bKshetra\ Mangala\b": "Kshetra Mung-guh-laa",
    r"\bKshetra\ Kapilas\b": "Kshetra Kuh-pee-laas",
    r"\bKshetra\ Hingula\b": "Kshetra Hing-goo-laa",
    r"\bPitha\ Jagannath\b": "Pitha Jug-un-naath",
    r"\bPitha\ Gupteswar\b": "Pitha Goop-tesh-wurr",
    r"\bPitha\ Charchika\b": "Pitha Chur-chih-kaa",
    r"\bLord\ Jagannath\b": "Lord Jug-un-naath",
    r"\bBiraja\ Kshetra\b": "Bih-ruh-jaa Kshay-truh",
    r"\bMaa\ Bhattarika\b": "Maa Bhut-taa-rih-kaa",
    r"\bCuttack\ Chandi\b": "Kuh-tuck Chun-dee",
    r"\bBaba\ Gupteswar\b": "Baa-baa Goop-tesh-wurr",
    r"\bNarasimhanatha\b": "Nuh-ruh-sing-huh-naath",
    r"\bParasurameswar\b": "Puh-ruh-shoo-raam-esh-wurr",
    r"\bNilakantheswar\b": "Nee-luh-kun-thesh-wurr",
    r"\bMaa\ Taratarini\b": "Maa Taa-raa Taa-rih-nee",
    r"\bMaa\ Harachandi\b": "Maa Huh-ruh-chun-dee",
    r"\bMaa\ Ramachandi\b": "Maa Raa-muh-chun-dee",
    r"\bKanchi\ Ganesha\b": "Kaan-chee Guh-nay-shuh",
    r"\bAnandabhairavi\b": "Aa-nun-duh-bhy-ruh-vee",
    r"\bMarkandeyeswar\b": "Maar-kun-day-yesh-wurr",
    r"\bJhankad\ Sarala\b": "Jhung-kud Saa-ruh-laa",
    r"\bTripurasundari\b": "Tree-poo-ruh-soon-duh-ree",
    r"\bMaa\ Lankeswari\b": "Maa Lung-kesh-wuh-ree",
    r"\bChhera\ Pahanra\b": "Chhay-raa Puh-hun-raa",
    r"\bPati\ Mohapatra\b": "Puh-tee Moh-huh-paa-truh",
    r"\bChangada\ Mekap\b": "Chung-guh-daa May-kup",
    r"\bDwarapala\ Puja\b": "Dwaa-ruh-paa-luh Poo-jaa",
    r"\bChacheri\ Besha\b": "Chuh-chay-ree Bay-shuh",
    r"\bBanayaga\ Yatra\b": "Buh-nuh-yaa-guh Yaah-traa",
    r"\bKhakhara\ Deula\b": "Khaa-khuh-raa Day-oo-luh",
    r"\bGaruda\ Stambha\b": "Guh-roo-duh Stum-bhuh",
    r"\bRaja\ Sankranti\b": "Ruh-joh Sung-kraan-tee",
    r"\bKumara\ Purnima\b": "Koo-maar Poor-nih-maa",
    r"\bPrathamashtami\b": "Pruh-thuh-maash-tuh-mee",
    r"\bPana\ Sankranti\b": "Puh-naa Sung-kraan-tee",
    r"\bSaraswati\ Puja\b": "Suh-rus-wuh-tee Poo-jaa",
    r"\bVijaya\ Dashami\b": "Vih-juh-yuh Dush-mee",
    r"\bBhalukuni\ Osha\b": "Bhaa-loo-koo-nee Oh-shaa",
    r"\bRekha\ Panchami\b": "Ray-khaa Pun-chuh-mee",
    r"\bAswina\ Purnima\b": "Aash-wih-nuh Poor-nih-maa",
    r"\bBhatru\ Dwitiya\b": "Bhaa-troo Dwee-tee-yaa",
    r"\bGovardhan\ Puja\b": "Goh-vur-dhun Poo-jaa",
    r"\bKaduasuni\ Mela\b": "Kuh-doo-aa-soo-nee May-laa",
    r"\bSukhila\ Prasad\b": "Soo-khee-laa Pruh-saadh",
    r"\bMadaranga\ Saga\b": "Muh-duh-rung-gaa Saa-guh",
    r"\bChingudi\ Malai\b": "Ching-goo-dee Muh-lye",
    r"\bChingudi\ Jhola\b": "Ching-goo-dee Jhoh-luh",
    r"\bBaripada\ Mudhi\b": "Baa-ree-puh-daa Moo-dhee",
    r"\bKhajuri\ Khatta\b": "Khuh-joo-ree Khut-taa",
    r"\bPipili\ Chandua\b": "Pee-pee-lee Chun-doo-aa",
    r"\bKumkum\ Mohanty\b": "Koom-koom Moh-hun-tee",
    r"\bParalakhemundi\b": "Paa-ruh-laa-khem-oon-dee",
    r"\bKalijai\ Island\b": "Kaa-lee-jye Island",
    r"\bSatkosia\ Gorge\b": "Sut-koh-see-aa Gorge",
    r"\bKabisuryanagar\b": "Kuh-bee-soor-yuh-nuh-gur",
    r"\bNischintakoili\b": "Neesh-chin-tuh-koy-lee",
    r"\bQueen\ Karuwaki\b": "Queen Kah-roo-vah-kee",
    r"\bEmperor\ Ashoka\b": "Emperor Uh-shoh-kuh",
    r"\bYajati\ Keshari\b": "Yuh-jaa-tee Kay-shuh-ree",
    r"\bNarasimha\ Deva\b": "Nuh-ruh-sing-huh Day-vuh",
    r"\bChakhi\ Khuntia\b": "Chuh-khee Khoon-tee-aa",
    r"\bGopabandhu\ Das\b": "Goh-puh-bun-dhoo Daas",
    r"\bMadhusudan\ Das\b": "Maa-dhoo-soo-dun Daas",
    r"\bRamakanta\ Rath\b": "Raa-muh-kaan-tuh Ruth",
    r"\bNilakantha\ Das\b": "Nee-luh-kun-thuh Daas",
    r"\bSharabhapuriya\b": "Shuh-ruh-bhuh-poo-ree-yuh",
    r"\bFirst\ of\ April\b": "First of April",
    r"\bDandi\ Ramayana\b": "Dun-dee Raa-maa-yuh-nuh",
    r"\bOdia\ Bhagavata\b": "Oh-dee-aa Bhaa-guh-vuh-tuh",
    r"\bYasovanta\ Dasa\b": "Yuh-shoh-vun-tuh Daas",
    r"\bUpendra\ Bhanja\b": "Oo-pen-dhruh Bhun-juh",
    r"\bBaladeva\ Ratha\b": "Buh-luh-dhev Ruh-thuh",
    r"\bAhe\ Nila\ Saila\b": "Aa-hay Nee-luh Sye-luh",
    r"\bPrabuddha\ Kabi\b": "Pruh-bood-dhuh Kuh-bee",
    r"\bMatira\ Manisha\b": "Maa-tih-ruh Muh-nee-shuh",
    r"\bMadhusudan\ Rao\b": "Maa-dhoo-soo-dun Row",
    r"\bKrishna\ Paksha\b": "Krush-nuh Puk-shuh",
    r"\bBrahma\ Muhurta\b": "Bruh-muh Moo-hoor-tuh",
    r"\bBiraja\ Panjika\b": "Bih-ruh-jaa Pun-jee-kaa",
    r"\bKhusire\ Thantu\b": "Khoo-shee-ray Thun-too",
    r"\bSuvarna\ Dweepa\b": "Soo-vur-nuh Dwee-puh",
    r"\bLord\ Gupteswar\b": "Lord Goop-tesh-wurr",
    r"\bLord\ Charchika\b": "Lord Chur-chih-kaa",
    r"\bMaa\ Balabhadra\b": "Maa Buhl-uh-bhuh-druh",
    r"\bBaba\ Jagannath\b": "Baba Jug-un-naath",
    r"\bBaba\ Charchika\b": "Baba Chur-chih-kaa",
    r"\bShree\ Lingaraj\b": "Shree Ling-guh-raaj",
    r"\bShree\ Subhadra\b": "Shree Soo-bhuh-dhrah",
    r"\bShree\ Lokanath\b": "Shree Loh-kuh-naath",
    r"\bSri\ Balabhadra\b": "Sri Buhl-uh-bhuh-druh",
    r"\bSri\ Bhattarika\b": "Sri Bhut-taa-rih-kaa",
    r"\bSri\ Taratarini\b": "Sri Taa-raa Taa-rih-nee",
    r"\bDevi\ Jagannath\b": "Devi Jug-un-naath",
    r"\bDevi\ Gupteswar\b": "Devi Goop-tesh-wurr",
    r"\bDevi\ Charchika\b": "Devi Chur-chih-kaa",
    r"\bMandir\ Mangala\b": "Mandir Mung-guh-laa",
    r"\bMandir\ Kapilas\b": "Mandir Kuh-pee-laas",
    r"\bMandir\ Hingula\b": "Mandir Hing-goo-laa",
    r"\bTemple\ Mangala\b": "Temple Mung-guh-laa",
    r"\bTemple\ Kapilas\b": "Temple Kuh-pee-laas",
    r"\bTemple\ Hingula\b": "Temple Hing-goo-laa",
    r"\bKshetra\ Biraja\b": "Kshetra Bih-ruh-jaa",
    r"\bKshetra\ Sarala\b": "Kshetra Saa-ruh-laa",
    r"\bKshetra\ Tarini\b": "Kshetra Taa-rih-nee",
    r"\bKshetra\ Chandi\b": "Kshetra Chun-dee",
    r"\bPitha\ Lingaraj\b": "Pitha Ling-guh-raaj",
    r"\bPitha\ Subhadra\b": "Pitha Soo-bhuh-dhrah",
    r"\bPitha\ Lokanath\b": "Pitha Loh-kuh-naath",
    r"\bDevi\ Subhadra\b": "Day-vee Soo-bhuh-dhrah",
    r"\bSarala\ Chandi\b": "Saa-ruh-laa Chun-dee",
    r"\bMaa\ Charchika\b": "Maa Chur-chih-kaa",
    r"\bLord\ Lingaraj\b": "Lord Ling-guh-raaj",
    r"\bAkhandalamani\b": "Uh-khun-duh-luh-muh-nee",
    r"\bNrusinghanath\b": "Nroo-sing-huh-naath",
    r"\bChandrasekhar\b": "Chun-dhruh-shay-khur",
    r"\bMajhighariani\b": "Maa-jee-ghuh-ree-yaa-nee",
    r"\bMaa\ Sureswari\b": "Maa Soo-resh-wuh-ree",
    r"\bGoddess\ Durga\b": "Gaw-dess Door-gaa",
    r"\bMaa\ Saraswati\b": "Maa Suh-rus-wuh-tee",
    r"\bMaa\ Ugra\ Tara\b": "Maa Oog-ruh Taa-raa",
    r"\bMaa\ Bhagabati\b": "Maa Bhaa-guh-buh-tee",
    r"\bBrahmani\ Devi\b": "Bruh-muh-nee Day-vee",
    r"\bAkhanda\ Mekap\b": "Uh-khun-duh May-kup",
    r"\bTadhau\ Karana\b": "Tuh-dhow Kuh-ruh-nuh",
    r"\bMangala\ Alati\b": "Mung-guh-laa Aa-luh-tee",
    r"\bSandhya\ Alati\b": "Sun-dhyaa Aa-luh-tee",
    r"\bSandhya\ Dhupa\b": "Sun-dhyaa Dhoo-puh",
    r"\bKamakhyabeshi\b": "Kaa-maa-khyaa-bay-shee",
    r"\bHera\ Panchami\b": "Hay-raa Pun-chuh-mee",
    r"\bBhoga\ Mandapa\b": "Bhoh-guh Mun-duh-puh",
    r"\bMukti\ Mandapa\b": "Mook-tee Mun-duh-puh",
    r"\bAruna\ Stambha\b": "Uh-roo-nuh Stum-bhuh",
    r"\bGundicha\ Ghar\b": "Goon-dih-chaa Ghur",
    r"\bChappan\ Chuli\b": "Chup-pun Choo-lee",
    r"\bGhanta\ Kahali\b": "Ghun-taa Kaa-haa-lee",
    r"\bChandan\ Yatra\b": "Chun-dun Yaah-traa",
    r"\bSnana\ Purnima\b": "Snaan Poor-nih-maa",
    r"\bBoita\ Bandana\b": "Boy-tuh Bun-duh-nuh",
    r"\bRaja\ Festival\b": "Ruh-joh Festival",
    r"\bNuakhai\ Juhar\b": "Noo-aa-khye Joo-haar",
    r"\bNuakhai\ Parab\b": "Noo-aa-khye Puh-rub",
    r"\bKumar\ Purnima\b": "Koo-maar Poor-nih-maa",
    r"\bDola\ Festival\b": "Doh-laa Festival",
    r"\bSitala\ Sasthi\b": "Shee-tuh-laa Sush-thee",
    r"\bGamha\ Purnima\b": "Gum-haa Poor-nih-maa",
    r"\bRakhi\ Purnima\b": "Raa-khee Poor-nih-maa",
    r"\bMagha\ Saptami\b": "Maa-ghuh Sup-tuh-mee",
    r"\bDutta\ Tritiya\b": "Doo-tee-yaa Tree-tee-yaa",
    r"\bSabitri\ Vrata\b": "Saa-bih-tree Vruh-tuh",
    r"\bSavitri\ Brata\b": "Saa-bih-tree Bruh-tuh",
    r"\bSudasha\ Vrata\b": "Soo-duh-shaa Vruh-tuh",
    r"\bSomabar\ Vrata\b": "Soh-muh-baar Vruh-tuh",
    r"\bChaitra\ Parba\b": "Chye-truh Pur-buh",
    r"\bPusha\ Purnima\b": "Poo-shuh Poor-nih-maa",
    r"\bDevalaya\ Mela\b": "Day-vuh-luh-yuh May-laa",
    r"\bPakhala\ Bhata\b": "Puh-khaa-luh Bhaa-tuh",
    r"\bMachha\ Besara\b": "Maach-uh Bay-suh-ruh",
    r"\bKankada\ Jhola\b": "Kuhn-kuh-daa Jhoh-luh",
    r"\bChhena\ Kakara\b": "Chhay-naa Kaa-kuh-raa",
    r"\bChakuli\ Pitha\b": "Chuh-koo-lee Pee-thaa",
    r"\bBudha\ Chakuli\b": "Boo-dhaa Chuh-koo-lee",
    r"\bGaintha\ Pitha\b": "Gye-n-thaa Pee-thaa",
    r"\bPanchaphutana\b": "Pun-chuh-foo-tuh-nuh",
    r"\bKankada\ Jholo\b": "Kuhn-kuh-daa Jhoh-loh",
    r"\bBoiti\ Kakharu\b": "Boy-tee Kaa-khuh-roo",
    r"\bChhena\ Kheeri\b": "Chhay-naa Khee-ree",
    r"\bChaula\ Kheeri\b": "Chow-luh Khee-ree",
    r"\bTomato\ Khatta\b": "Tomato Khut-taa",
    r"\bRavana\ Chhaya\b": "Raa-vun Chhaa-yaa",
    r"\bApplique\ Work\b": "Ap-lee-kay Work",
    r"\bStone\ Carving\b": "Stone Caar-ving",
    r"\bKhandua\ Patta\b": "Khun-doo-aa Put-tuh",
    r"\bMangalacharan\b": "Mung-guh-laa-chuh-run",
    r"\bJagatsinghpur\b": "Juh-gut-singh-poor",
    r"\bPrachi\ Valley\b": "Praa-chee Valley",
    r"\bBarabati\ Fort\b": "Baa-ruh-baa-tee Fort",
    r"\bChudanga\ Gada\b": "Choo-dung-guh Guh-duh",
    r"\bRaibania\ Fort\b": "Rye-baa-nee-aa Fort",
    r"\bJoranda\ Falls\b": "Joh-run-daa Falls",
    r"\bKamakhyanagar\b": "Kaa-maa-khyaa-nuh-gur",
    r"\bBrajarajnagar\b": "Bruh-juh-raaj-nuh-gur",
    r"\bKakatpur\ Town\b": "Kaa-kut-poor Town",
    r"\bKrushnaprasad\b": "Krush-nuh-pruh-saadh",
    r"\bGanga\ Dynasty\b": "Gung-gaa Dynasty",
    r"\bEastern\ Ganga\b": "Eastern Gung-gaa",
    r"\bPaika\ Bidroha\b": "Pye-kuh Bee-droh-huh",
    r"\bJayee\ Rajguru\b": "Juh-yee Raaj-goo-roo",
    r"\bRadhanath\ Ray\b": "Raa-dhaa-naath Rye",
    r"\bSwabhaba\ Kabi\b": "Swuh-bhaa-vuh Kuh-bee",
    r"\bUtkal\ Keshari\b": "Oot-kuhl Kay-shuh-ree",
    r"\bMaa\ Rama\ Devi\b": "Maa Raa-maa Day-vee",
    r"\bBisu\ Maharana\b": "Bee-soo Muh-haa-raa-naa",
    r"\bChandi\ Purana\b": "Chun-dee Poo-raa-nuh",
    r"\bBalarama\ Dasa\b": "Buhl-uh-raam Daas",
    r"\bKaivalya\ Gita\b": "Kye-buhl-yuh Gee-taa",
    r"\bSunya\ Samhita\b": "Shoon-yuh Sum-hee-taa",
    r"\bGopalakrushna\b": "Goh-paa-luh-krush-nuh",
    r"\bAlekha\ Mahima\b": "Uh-lay-khuh Muh-hee-maa",
    r"\bMahima\ Dharma\b": "Muh-hee-maa Dhur-muh",
    r"\bMahima\ Gosain\b": "Muh-hee-maa Goh-saayn",
    r"\bChilika\ Kavya\b": "Chih-lih-kaa Kaav-yuh",
    r"\bKichaka\ Badha\b": "Kee-chuh-kuh Buh-dhuh",
    r"\bHarijan\ Novel\b": "Huh-ree-jun Novel",
    r"\bShukla\ Paksha\b": "Shook-luh Puk-shuh",
    r"\bKalinga\ Sagar\b": "Kuh-ling-guh Saa-gur",
    r"\bPana\ Gua\ Thoi\b": "Puh-naa Goo-aa Toy",
    r"\bPana\ Gua\ Khai\b": "Puh-naa Goo-aa Khye",
    r"\bUtkala\ Janani\b": "Oot-kuhl Juh-nuh-nee",
    r"\bLord\ Subhadra\b": "Lord Soo-bhuh-dhrah",
    r"\bLord\ Lokanath\b": "Lord Loh-kuh-naath",
    r"\bMaa\ Jagannath\b": "Maa Jug-un-naath",
    r"\bMaa\ Gupteswar\b": "Maa Goop-tesh-wurr",
    r"\bBaba\ Lingaraj\b": "Baba Ling-guh-raaj",
    r"\bBaba\ Subhadra\b": "Baba Soo-bhuh-dhrah",
    r"\bBaba\ Lokanath\b": "Baba Loh-kuh-naath",
    r"\bShree\ Mangala\b": "Shree Mung-guh-laa",
    r"\bShree\ Kapilas\b": "Shree Kuh-pee-laas",
    r"\bShree\ Hingula\b": "Shree Hing-goo-laa",
    r"\bSri\ Jagannath\b": "Sri Jug-un-naath",
    r"\bSri\ Gupteswar\b": "Sri Goop-tesh-wurr",
    r"\bSri\ Charchika\b": "Sri Chur-chih-kaa",
    r"\bDevi\ Lingaraj\b": "Devi Ling-guh-raaj",
    r"\bDevi\ Lokanath\b": "Devi Loh-kuh-naath",
    r"\bMandir\ Biraja\b": "Mandir Bih-ruh-jaa",
    r"\bMandir\ Sarala\b": "Mandir Saa-ruh-laa",
    r"\bMandir\ Tarini\b": "Mandir Taa-rih-nee",
    r"\bMandir\ Chandi\b": "Mandir Chun-dee",
    r"\bTemple\ Biraja\b": "Temple Bih-ruh-jaa",
    r"\bTemple\ Sarala\b": "Temple Saa-ruh-laa",
    r"\bTemple\ Tarini\b": "Temple Taa-rih-nee",
    r"\bTemple\ Chandi\b": "Temple Chun-dee",
    r"\bPitha\ Mangala\b": "Pitha Mung-guh-laa",
    r"\bPitha\ Kapilas\b": "Pitha Kuh-pee-laas",
    r"\bPitha\ Hingula\b": "Pitha Hing-goo-laa",
    r"\bPurushottama\b": "Poo-roo-shoht-tuh-muh",
    r"\bSakshi\ Gopal\b": "Saak-shee Goh-paal",
    r"\bSamaleshwari\b": "Suh-muhl-esh-wuh-ree",
    r"\bSarala\ Pitha\b": "Saa-ruh-laa Pee-thuh",
    r"\bKatak\ Chandi\b": "Kuh-tuck Chun-dee",
    r"\bKhambeshwari\b": "Khum-besh-wuh-ree",
    r"\bMahavinayaka\b": "Maa-haa-vih-naa-yuh-kuh",
    r"\bBaladeva\ Jew\b": "Buhl-uh-dev-jew",
    r"\bBhaskareswar\b": "Bhaas-kuh-resh-wurr",
    r"\bManikeshwari\b": "Maa-nih-kesh-wuh-ree",
    r"\bDakshinakali\b": "Duk-shih-nuh Kaa-lee",
    r"\bBhubaneswari\b": "Bhoo-buh-nesh-wuh-ree",
    r"\bBiraja\ Peeth\b": "Bih-ruh-jaa Peeth",
    r"\bVimala\ Peeth\b": "Bih-muh-laa Peeth",
    r"\bMaa\ Metakani\b": "Maa May-tuh-kuh-nee",
    r"\bSaptamatruka\b": "Sup-tuh-maat-roo-kaa",
    r"\bMaa\ Chamunda\b": "Maa Chaa-moon-daa",
    r"\bPahandi\ Bije\b": "Puh-hun-dee Bee-jay",
    r"\bHadapa\ Nayak\b": "Huh-duh-puh Naa-yuck",
    r"\bDeula\ Karana\b": "Day-oo-luh Kuh-ruh-nuh",
    r"\bGopala\ Bhoga\b": "Goh-paa-luh Bhohg",
    r"\bSakala\ Dhupa\b": "Suh-kuh-luh Dhoo-puh",
    r"\bChandan\ Lagi\b": "Chun-dun Laa-gee",
    r"\bNiladri\ Bije\b": "Nee-laa-dree Bee-jay",
    r"\bNabakalebara\b": "Nuh-buh-kuhl-eh-buh-ruh",
    r"\bNavakalevara\b": "Nuh-buh-kuhl-eh-buh-ruh",
    r"\bNata\ Mandapa\b": "Naa-tuh Mun-duh-puh",
    r"\bVyaghradwara\b": "Vyaa-ghruh-dwaa-ruh",
    r"\bBaisipahacha\b": "Bye-see-puh-haa-chuh",
    r"\bRohini\ Kunda\b": "Roh-hee-nee Koon-duh",
    r"\bBata\ Mangala\b": "Buh-tuh Mung-guh-laa",
    r"\bChakratirtha\b": "Chuk-ruh-teer-thuh",
    r"\bBahuda\ Yatra\b": "Baa-hoo-daa Yaah-traa",
    r"\bBhudaha\ Raja\b": "Bhoo-duh-haa Ruh-joh",
    r"\bDola\ Purnima\b": "Doh-laa Poor-nih-maa",
    r"\bJhulan\ Yatra\b": "Jhoo-lun Yaah-traa",
    r"\bJoranda\ Mela\b": "Joh-run-daa May-laa",
    r"\bBada\ Ekadasi\b": "Buh-duh Ay-kaa-duh-shee",
    r"\bSamba\ Dasami\b": "Saam-buh Dush-mee",
    r"\bChappan\ Bhog\b": "Chup-pun Bhohg",
    r"\bBasi\ Pakhala\b": "Baa-see Puh-khaa-luh",
    r"\bSaja\ Pakhala\b": "Suh-jaa Puh-khaa-luh",
    r"\bDahi\ Pakhala\b": "Duh-hee Puh-khaa-luh",
    r"\bMachha\ Jhola\b": "Maach-uh Jhoh-luh",
    r"\bChhena\ Jhili\b": "Chhay-naa Jhee-lee",
    r"\bKakara\ Pitha\b": "Kaa-kuh-raa Pee-thaa",
    r"\bEnduri\ Pitha\b": "En-doo-ree Pee-thaa",
    r"\bChitau\ Pitha\b": "Chih-tow Pee-thaa",
    r"\bSaru\ Chakuli\b": "Saa-roo Chuh-koo-lee",
    r"\bChhena\ Mudki\b": "Chhay-naa Mood-kee",
    r"\bChandrakanti\b": "Chun-dhruh-kaan-tee",
    r"\bBara\ Ghuguni\b": "Buh-raa Ghoo-ghoo-nee",
    r"\bTanka\ Torani\b": "Tun-kaa Toh-ruh-nee",
    r"\bGaram\ Masala\b": "Guh-rum Muh-saa-laa",
    r"\bKancha\ Lanka\b": "Kaan-chaa Lung-kaa",
    r"\bUsuna\ Chaula\b": "Oo-soo-naa Chow-luh",
    r"\bAmrutabhanda\b": "Uhm-roo-tuh-bhun-daa",
    r"\bPani\ Kakharu\b": "Paa-nee Kaa-khuh-roo",
    r"\bKolatha\ Dali\b": "Koh-luh-thuh Daa-lee",
    r"\bKandula\ Dali\b": "Kuhn-doo-luh Daa-lee",
    r"\bLabanga\ Lata\b": "Luh-bung-guh Luh-taa",
    r"\bChhena\ Payas\b": "Chhay-naa Pye-us",
    r"\bDahi\ Baigana\b": "Duh-hee Bye-guh-nuh",
    r"\bBhendi\ Bhaja\b": "Bhen-dee Bhaa-jaa",
    r"\bKalara\ Bhaja\b": "Kuh-luh-raa Bhaa-jaa",
    r"\bPotala\ Bhaja\b": "Poh-tuh-luh Bhaa-jaa",
    r"\bOdissi\ Dance\b": "Oh-dih-see Dance",
    r"\bOdissi\ Music\b": "Oh-dih-see Music",
    r"\bChaiti\ Ghoda\b": "Chye-tee Ghoh-daa",
    r"\bLacquer\ Toys\b": "Luh-kur Toys",
    r"\bGolden\ Grass\b": "Golden Grass",
    r"\bKotpad\ Weave\b": "Koht-paad Weave",
    r"\bDhauli\ Hills\b": "Dhow-lee Hills",
    r"\bChilika\ Lake\b": "Chih-lih-kaa Lake",
    r"\bSubarnarekha\b": "Soo-bur-nuh-ray-khaa",
    r"\bBudhabalanga\b": "Boo-dhaa-buhl-ung-guh",
    r"\bGandhamardan\b": "Gun-dhuh-mur-dun",
    r"\bMahendragiri\b": "Muh-hen-druh-gih-ree",
    r"\bBhitarkanika\b": "Bhee-tur-kuh-nih-kaa",
    r"\bDuduma\ Falls\b": "Doo-doo-muh Falls",
    r"\bGolden\ Beach\b": "Golden Beach",
    r"\bBhawanipatna\b": "Bhuh-waa-nee-put-naa",
    r"\bKhariar\ Road\b": "Khuh-ree-aar Road",
    r"\bBiramitrapur\b": "Bih-ruh-mee-truh-poor",
    r"\bKishorenagar\b": "Kee-shohr-nuh-gur",
    r"\bNarasinghpur\b": "Nuh-ruh-singh-poor",
    r"\bMahakalapada\b": "Muh-haa-kuh-luh-puh-daa",
    r"\bRaghunathpur\b": "Ruh-ghoo-naath-poor",
    r"\bMukunda\ Deva\b": "Moo-koon-duh Day-vuh",
    r"\bBhoi\ Dynasty\b": "Boy Dynasty",
    r"\bSurendra\ Sai\b": "Soo-ren-dhruh Saa-ee",
    r"\bLaxman\ Nayak\b": "Lux-mun Naa-yuck",
    r"\bUtkal\ Gourav\b": "Oot-kuhl Gow-ruv",
    r"\bBiju\ Patnaik\b": "Bee-joo Put-naa-yick",
    r"\bPratibha\ Ray\b": "Pruh-tih-bhaa Rye",
    r"\bHarihar\ Dash\b": "Huh-ree-hur Daash",
    r"\bNala\ Dynasty\b": "Nuh-luh Dynasty",
    r"\bGita\ Govinda\b": "Gee-tuh Goh-vin-duh",
    r"\bGeetagovinda\b": "Gee-tuh Goh-vin-duh",
    r"\bLaxmi\ Purana\b": "Lux-mee Poo-raa-nuh",
    r"\bAchyutananda\b": "Uh-chyoo-taa-nun-duh",
    r"\bSishu\ Ananta\b": "Shee-shoo Uh-nun-tuh",
    r"\bKabi\ Samrata\b": "Kuh-bee Sum-raat",
    r"\bPrayaschitta\b": "Praa-yush-chit-tuh",
    r"\bChandrabhaga\b": "Chun-dhruh-bhaa-gaa",
    r"\bKesaba\ Koili\b": "Kay-shuh-buh Koy-lee",
    r"\bAmruta\ Phala\b": "Uhm-roo-tuh Fuhl",
    r"\bKonarka\ Poem\b": "Koh-naark Poem",
    r"\bKabi\ Sekhara\b": "Kuh-bee Say-khuh-ruh",
    r"\bSubha\ Sakala\b": "Shoo-bhuh Suh-khaa-luh",
    r"\bAa\ Ka\ Ma\ Boi\b": "Aa Kaa Maa Boy",
    r"\bLord\ Mangala\b": "Lord Mung-guh-laa",
    r"\bLord\ Kapilas\b": "Lord Kuh-pee-laas",
    r"\bLord\ Hingula\b": "Lord Hing-goo-laa",
    r"\bMaa\ Lingaraj\b": "Maa Ling-guh-raaj",
    r"\bMaa\ Subhadra\b": "Maa Soo-bhuh-dhrah",
    r"\bMaa\ Lokanath\b": "Maa Loh-kuh-naath",
    r"\bBaba\ Mangala\b": "Baba Mung-guh-laa",
    r"\bBaba\ Kapilas\b": "Baba Kuh-pee-laas",
    r"\bBaba\ Hingula\b": "Baba Hing-goo-laa",
    r"\bShree\ Biraja\b": "Shree Bih-ruh-jaa",
    r"\bShree\ Sarala\b": "Shree Saa-ruh-laa",
    r"\bShree\ Tarini\b": "Shree Taa-rih-nee",
    r"\bShree\ Chandi\b": "Shree Chun-dee",
    r"\bSri\ Lingaraj\b": "Sri Ling-guh-raaj",
    r"\bSri\ Subhadra\b": "Sri Soo-bhuh-dhrah",
    r"\bSri\ Lokanath\b": "Sri Loh-kuh-naath",
    r"\bDevi\ Mangala\b": "Devi Mung-guh-laa",
    r"\bDevi\ Kapilas\b": "Devi Kuh-pee-laas",
    r"\bDevi\ Hingula\b": "Devi Hing-goo-laa",
    r"\bPitha\ Biraja\b": "Pitha Bih-ruh-jaa",
    r"\bPitha\ Sarala\b": "Pitha Saa-ruh-laa",
    r"\bPitha\ Tarini\b": "Pitha Taa-rih-nee",
    r"\bPitha\ Chandi\b": "Pitha Chun-dee",
    r"\bNilamadhaba\b": "Neel-uh-maadh-uh-vuh",
    r"\bNeelamadhav\b": "Neel-uh-maadh-uh-vuh",
    r"\bPurusottama\b": "Poo-roo-shoht-tuh-muh",
    r"\bBiraja\ Devi\b": "Bih-ruh-jaa Day-vee",
    r"\bSamaleswari\b": "Suh-muhl-esh-wuh-ree",
    r"\bMaa\ Samalei\b": "Maa Suh-muh-lye",
    r"\bMaa\ Mangala\b": "Maa Mung-guh-laa",
    r"\bMaa\ Hingula\b": "Maa Hing-goo-laa",
    r"\bDhabaleswar\b": "Dhuh-buhl-esh-wurr",
    r"\bHarishankar\b": "Huh-ree-shun-kurr",
    r"\bMaa\ Marichi\b": "Maa Muh-ree-chee",
    r"\bMaa\ Kalijai\b": "Maa Kaa-lee-jye",
    r"\bKantabaunsa\b": "Kun-tuh-bown-suh",
    r"\bPataneswari\b": "Puh-tuh-nesh-wuh-ree",
    r"\bMahalakshmi\b": "Maa-haa-lux-mee",
    r"\bGhanashyama\b": "Ghuh-nuh-shyaam",
    r"\bMadhusudana\b": "Maa-dhoo-soo-dun",
    r"\bHrushikesha\b": "Hroo-shee-kay-shuh",
    r"\bBataganesha\b": "Buh-tuh-guh-nay-shuh",
    r"\bGhanteswari\b": "Ghun-tesh-wuh-ree",
    r"\bKanakadurga\b": "Kuh-nuh-kuh-door-gaa",
    r"\bChinnamasta\b": "Chihn-nuh-mus-taa",
    r"\bBagalamukhi\b": "Buh-guh-laa-moo-khee",
    r"\bKamalatmika\b": "Kuh-muh-laat-mih-kaa",
    r"\bGramadevata\b": "Graa-muh-day-vuh-tuh",
    r"\bGramadevati\b": "Graa-muh-day-vuh-tee",
    r"\bIsta\ Devata\b": "Eesh-tuh Day-vuh-tuh",
    r"\bKula\ Devata\b": "Koo-luh Day-vuh-tuh",
    r"\bKhetra\ Pala\b": "Kshay-truh Paa-luh",
    r"\bBalunkeswar\b": "Buh-loon-kesh-wurr",
    r"\bNandighosha\b": "Nun-dih-ghoh-shuh",
    r"\bDarpadalana\b": "Dur-puh-duh-luh-nuh",
    r"\bPadma\ Besha\b": "Pud-muh Bay-shuh",
    r"\bAdhara\ Pana\b": "Uh-dhuh-raa Puh-naa",
    r"\bDaru\ Brahma\b": "Daa-roo Bruh-muh",
    r"\bRekha\ Deula\b": "Ray-khaa Day-oo-luh",
    r"\bPidha\ Deula\b": "Pee-dhaa Day-oo-luh",
    r"\bNeelachakra\b": "Nee-luh-chuk-ruh",
    r"\bSinghadwara\b": "Sing-huh-dwaa-ruh",
    r"\bAnandabazar\b": "Aa-nun-duh-buh-zaar",
    r"\bKurma\ Bedha\b": "Koor-muh Bay-dhaa",
    r"\bEmara\ Matha\b": "Ay-muhr Muth",
    r"\bRatha\ Jatra\b": "Ruth Yaah-traa",
    r"\bChapa\ Khela\b": "Chaap Khel-uh",
    r"\bSnana\ Yatra\b": "Snaan Yaah-traa",
    r"\bPahili\ Raja\b": "Puh-hee-lee Ruh-joh",
    r"\bSitalsasthi\b": "Shee-tuhl-sush-thee",
    r"\bDhanu\ Jatra\b": "Dhuh-noo Jaah-traa",
    r"\bDhanu\ Yatra\b": "Dhuh-noo Yaah-traa",
    r"\bDanda\ Yatra\b": "Dun-duh Yaah-traa",
    r"\bDanda\ Parba\b": "Dun-duh Pur-buh",
    r"\bJanmashtami\b": "Juhn-maash-tuh-mee",
    r"\bRadhashtami\b": "Raa-dhaash-tuh-mee",
    r"\bGanesh\ Puja\b": "Guh-naysh Poo-jaa",
    r"\bShiva\ Ratri\b": "Shih-vuh Raat-ree",
    r"\bJagara\ Mela\b": "Jaa-guh-ruh May-laa",
    r"\bBudhi\ Vrata\b": "Boo-dhee Vruh-tuh",
    r"\bAnla\ Navami\b": "Aam-laa Nuh-vuh-mee",
    r"\bHarida\ Dali\b": "Huh-ree-daa Daa-lee",
    r"\bKosala\ Saga\b": "Koh-suh-laa Saa-guh",
    r"\bLeutia\ Saga\b": "Lay-oo-tee-aa Saa-guh",
    r"\bPotala\ Rasa\b": "Poh-tuh-luh Ruh-suh",
    r"\bAloo\ Bharta\b": "Aa-loo Bhur-tuh",
    r"\bDahi\ Torani\b": "Duh-hee Toh-ruh-nee",
    r"\bMudhi\ Mansa\b": "Moo-dhee Maan-suh",
    r"\bChhena\ Poda\b": "Chhay-naa Paw-duh",
    r"\bChhena\ Gaja\b": "Chhay-naa Guh-jaa",
    r"\bMagaja\ Ladu\b": "Muh-guh-juh Luh-doo",
    r"\bArisa\ Pitha\b": "Uh-ree-saa Pee-thaa",
    r"\bSuji\ Kakara\b": "Soo-jee Kaa-kuh-raa",
    r"\bManda\ Pitha\b": "Mun-daa Pee-thaa",
    r"\bChaula\ Bara\b": "Chow-luh Buh-raa",
    r"\bChhena\ Pana\b": "Chhay-naa Puh-naa",
    r"\bGolamaricha\b": "Goh-luh-muh-ree-chuh",
    r"\bArua\ Chaula\b": "Aa-roo-aa Chow-luh",
    r"\bDahi\ Bhendi\b": "Duh-hee Bhen-dee",
    r"\bAmba\ Khatta\b": "Aam-baa Khut-taa",
    r"\bBharat\ Lila\b": "Bhuhr-ut Lee-laa",
    r"\bGhoda\ Nacha\b": "Ghoh-daa Naa-chuh",
    r"\bBaunsa\ Rani\b": "Bown-suh Raa-nee",
    r"\bJodi\ Sankha\b": "Joh-dee Shung-khuh",
    r"\bPattachitra\b": "Put-tuh-chih-truh",
    r"\bRaghurajpur\b": "Ruh-ghoo-raaj-poor",
    r"\bSabai\ Grass\b": "Suh-bye Grass",
    r"\bManiabandhi\b": "Maa-nee-aa-bun-dhee",
    r"\bTussar\ Silk\b": "Tuh-suhr Silk",
    r"\bBatu\ Nrutya\b": "Buh-too Nroot-yuh",
    r"\bBhikari\ Bal\b": "Bhee-kaa-ree Bahl",
    r"\bJaganathpur\b": "Juh-guh-naath-poor",
    r"\bBhubaneswar\b": "Bhoo-buh-neh-shwurr",
    r"\bNabarangpur\b": "Nuh-buh-rung-poor",
    r"\bMangalajodi\b": "Mung-guh-luh-joh-dee",
    r"\bSisupalgarh\b": "Shih-shoo-paal-gud",
    r"\bHirakud\ Dam\b": "Hee-raa-kood Dam",
    r"\bMandira\ Dam\b": "Mun-dih-raa Dam",
    r"\bRengali\ Dam\b": "Ren-gaa-lee Dam",
    r"\bBellaguntha\b": "Bel-luh-goon-thaa",
    r"\bDigapahandi\b": "Dih-guh-puh-hun-dee",
    r"\bBhanjanagar\b": "Bhun-juh-nuh-gur",
    r"\bBuguda\ Town\b": "Boo-goo-daa Town",
    r"\bG\ Udayagiri\b": "Jee Oo-duh-yuh-gih-ree",
    r"\bDunguripali\b": "Doon-goo-ree-puh-lee",
    r"\bChhendipada\b": "Chhen-dee-puh-daa",
    r"\bKhurda\ Road\b": "Khoor-dhaa Road",
    r"\bPipili\ Town\b": "Pee-pee-lee Town",
    r"\bPattamundai\b": "Put-tuh-moon-dye",
    r"\bDhamra\ Port\b": "Dhum-raa Port",
    r"\bChandashoka\b": "Chun-duh-shoh-kuh",
    r"\bDharmashoka\b": "Dhur-muh-shoh-kuh",
    r"\bKalinga\ War\b": "Kuh-ling-guh War",
    r"\bHathigumpha\b": "Haa-thee-goom-faa",
    r"\bBhauma\ Kara\b": "Bhow-muh Kuh-ruh",
    r"\bAnantavarma\b": "Uh-nun-tuh-vur-maa",
    r"\bMadho\ Singh\b": "Maa-dhoh Singh",
    r"\bRendo\ Majhi\b": "Ren-doh Maa-jee",
    r"\bBirsa\ Munda\b": "Beer-saa Moon-daa",
    r"\bSarala\ Devi\b": "Saa-ruh-laa Day-vee",
    r"\bSailodbhava\b": "Sye-lohd-bhuh-vuh",
    r"\bUtkal\ Divas\b": "Oot-kuhl Dee-vus",
    r"\bSarala\ Dasa\b": "Saa-ruh-laa Daas",
    r"\bAnanta\ Dasa\b": "Uh-nun-tuh Daas",
    r"\bPanchasakha\b": "Puhn-chuh-suh-khaa",
    r"\bLavanyavati\b": "Luh-vun-yuh-vuh-tee",
    r"\bDinakrushna\b": "Dih-nuh-krush-nuh",
    r"\bRasakallola\b": "Ruh-suh-kuhl-loh-luh",
    r"\bDhauli\ Poem\b": "Dhow-lee Poem",
    r"\bMangalabara\b": "Mung-guh-luh-baa-ruh",
    r"\bSubha\ Ratri\b": "Shoo-bhuh Raat-ree",
    r"\bKenta\ Achha\b": "Ken-taa Aachh-aa",
    r"\bBhala\ Achhi\b": "Buhl-uh Aachh-ee",
    r"\bSwargadwara\b": "Swur-guh-dwaa-ruh",
    r"\bMahasamadhi\b": "Muh-haa-suh-maa-dhee",
    r"\bBali\ Island\b": "Baa-lee Island",
    r"\bBhai\ Bahani\b": "Bhye Buh-huh-nee",
    r"\bLord\ Biraja\b": "Lord Bih-ruh-jaa",
    r"\bLord\ Sarala\b": "Lord Saa-ruh-laa",
    r"\bLord\ Tarini\b": "Lord Taa-rih-nee",
    r"\bLord\ Chandi\b": "Lord Chun-dee",
    r"\bMaa\ Kapilas\b": "Maa Kuh-pee-laas",
    r"\bBaba\ Biraja\b": "Baba Bih-ruh-jaa",
    r"\bBaba\ Sarala\b": "Baba Saa-ruh-laa",
    r"\bBaba\ Tarini\b": "Baba Taa-rih-nee",
    r"\bBaba\ Chandi\b": "Baba Chun-dee",
    r"\bSri\ Mangala\b": "Sri Mung-guh-laa",
    r"\bSri\ Kapilas\b": "Sri Kuh-pee-laas",
    r"\bSri\ Hingula\b": "Sri Hing-goo-laa",
    r"\bDevi\ Biraja\b": "Devi Bih-ruh-jaa",
    r"\bDevi\ Sarala\b": "Devi Saa-ruh-laa",
    r"\bDevi\ Tarini\b": "Devi Taa-rih-nee",
    r"\bDevi\ Chandi\b": "Devi Chun-dee",
    r"\bDhana\ Ratna\b": "Dhuh-nuh Rut-nuh",
    r"\bSona\ Chandi\b": "Soh-naa Chun-dee",
    r"\bMoti\ Manika\b": "Moh-tee Maa-nih-kuh",
    r"\bJagannatha\b": "Jug-un-naath",
    r"\bBalabhadra\b": "Buhl-uh-bhuh-druh",
    r"\bSudarshana\b": "Soo-dur-shun",
    r"\bNilamadhav\b": "Neel-uh-maadh-uh-vuh",
    r"\bSakhigopal\b": "Saak-shee Goh-paal",
    r"\bMaa\ Biraja\b": "Maa Bih-ruh-jaa",
    r"\bMaa\ Sarala\b": "Maa Saa-ruh-laa",
    r"\bBhattarika\b": "Bhut-taa-rih-kaa",
    r"\bMaa\ Tarini\b": "Maa Taa-rih-nee",
    r"\bMaa\ Bimala\b": "Maa Bih-muh-laa",
    r"\bBaladevjew\b": "Buhl-uh-dev-jew",
    r"\bBrahmeswar\b": "Bruhm-esh-wurr",
    r"\bMukteshwar\b": "Mook-tesh-wurr",
    r"\bKedargouri\b": "Kay-dhaar-gow-ree",
    r"\bBaidyanath\b": "Bye-dyuh-naath",
    r"\bKapileswar\b": "Kuh-pih-lesh-wurr",
    r"\bGorakhnath\b": "Goh-rukh-naath",
    r"\bTaratarini\b": "Taa-raa Taa-rih-nee",
    r"\bHarachandi\b": "Huh-ruh-chun-dee",
    r"\bRamachandi\b": "Raa-muh-chun-dee",
    r"\bTrivikrama\b": "Trih-vih-kruh-muh",
    r"\bPadmanabha\b": "Pud-muh-naa-bhuh",
    r"\bBedha\ Kali\b": "Bay-dhaa Kaa-lee",
    r"\bKhirachora\b": "Khee-ruh-choh-raa",
    r"\bMaa\ Basuli\b": "Maa Baa-soo-lee",
    r"\bKalei\ Suna\b": "Kuh-lye Soo-naa",
    r"\bLankeswari\b": "Lung-kesh-wuh-ree",
    r"\bAdya\ Sevak\b": "Aa-dyuh Say-vuck",
    r"\bTaladhwaja\b": "Tuh-luh-dhwuh-juh",
    r"\bDebadalana\b": "Day-buh-duh-luh-nuh",
    r"\bRathakhala\b": "Ruth-uh-khaa-laa",
    r"\bBhoi\ Sevak\b": "Boy Say-vuck",
    r"\bPushpalaka\b": "Poosh-puh-luh-kuh",
    r"\bPasupalaka\b": "Puh-soo-puh-luh-kuh",
    r"\bTadapalagi\b": "Tuh-duh-puh-laa-gee",
    r"\bSurya\ Puja\b": "Soor-yuh Poo-jaa",
    r"\bSuna\ Besha\b": "Soo-naa Bay-shuh",
    r"\bHati\ Besha\b": "Haa-tee Bay-shuh",
    r"\bGaja\ Besha\b": "Guh-juh Bay-shuh",
    r"\bJagamohana\b": "Juh-guh-moh-hun",
    r"\bSnana\ Bedi\b": "Snaa-nuh Bay-dee",
    r"\bNilachakra\b": "Nee-luh-chuk-ruh",
    r"\bAshwadwara\b": "Ush-wuh-dwaa-ruh",
    r"\bHastidwara\b": "Hus-tih-dwaa-ruh",
    r"\bBada\ Danda\b": "Buh-duh Dun-duh",
    r"\bOdia\ Matha\b": "Oh-dee-aa Muth",
    r"\bSankirtana\b": "Sung-keer-tuh-nuh",
    r"\bAtharanala\b": "Uh-thuh-ruh-nuh-laa",
    r"\bSwetaganga\b": "Shway-tuh-gung-gaa",
    r"\bRath\ Yatra\b": "Ruth Yaah-traa",
    r"\bBali\ Jatra\b": "Baa-lee Jaah-traa",
    r"\bBali\ Yatra\b": "Baa-lee Yaah-traa",
    r"\bRaja\ Parba\b": "Ruh-joh Pur-buh",
    r"\bPothastami\b": "Poh-thaash-tuh-mee",
    r"\bDola\ Jatra\b": "Doh-laa Jaah-traa",
    r"\bDanda\ Nata\b": "Dun-duh Naa-tuh",
    r"\bChhau\ Nata\b": "Chhow Naa-tuh",
    r"\bDurga\ Puja\b": "Door-gaa Poo-jaa",
    r"\bRavan\ Podi\b": "Raa-vun Paw-dee",
    r"\bJahni\ Osha\b": "Jaah-nee Oh-shaa",
    r"\bMagha\ Mela\b": "Maa-ghuh May-laa",
    r"\bAji\ Kalika\b": "Aa-jee Kaa-lee-kaa",
    r"\bDeba\ Snana\b": "Day-buh Snaan",
    r"\bRadhastami\b": "Raa-dhaash-tuh-mee",
    r"\bMahaprasad\b": "Maa-haa-pruh-saadh",
    r"\bMitha\ Dali\b": "Mee-thaa Daa-lee",
    r"\bSaga\ Bhaja\b": "Saa-guh Bhaa-jaa",
    r"\bChhatu\ Rai\b": "Chhuch-too Rye",
    r"\bNadia\ Bara\b": "Nuh-dee-aa Buh-raa",
    r"\bBadi\ Chura\b": "Buh-dee Choo-raa",
    r"\bPuri\ Khaja\b": "Poo-ree Khaa-jaa",
    r"\bPoda\ Pitha\b": "Paw-duh Pee-thaa",
    r"\bKhira\ Gaja\b": "Khee-ruh Guh-jaa",
    r"\bSuji\ Halwa\b": "Soo-jee Huhl-waa",
    r"\bAloo\ Bhaja\b": "Aa-loo Bhaa-jaa",
    r"\bAmbula\ Rai\b": "Aam-boo-luh Rye",
    r"\bOuu\ Khatta\b": "Oh-oo Khut-taa",
    r"\bBell\ Metal\b": "Bell Meh-tl",
    r"\bHorn\ Craft\b": "Horn Craft",
    r"\bTerracotta\b": "Teh-ruh-kot-tuh",
    r"\bCoir\ Craft\b": "Koy-er Craft",
    r"\bSambalpuri\b": "Sum-buhl-poo-ree",
    r"\bBandhakala\b": "Bun-dhuh-kuh-laa",
    r"\bMatha\ Silk\b": "Muth-aa Silk",
    r"\bNimakhandi\b": "Nee-muh-khun-dee",
    r"\bOdra\ Desha\b": "Oh-druh Day-shuh",
    r"\bMayurbhanj\b": "Maa-yoor-bhunj",
    r"\bKendrapara\b": "Ken-drah-puh-raa",
    r"\bMalkangiri\b": "Muhl-kahn-gee-ree",
    r"\bNowrangpur\b": "Now-rung-poor",
    r"\bSubarnapur\b": "Soo-bur-nuh-poor",
    r"\bJharsuguda\b": "Jhaar-soo-goo-daa",
    r"\bSundargarh\b": "Soon-dur-gud",
    r"\bRushikulya\b": "Roo-shih-kool-yaa",
    r"\bDaya\ River\b": "Duh-yaa River",
    r"\bVamsadhara\b": "Vum-suh-dhaa-raa",
    r"\bBansadhara\b": "Buhn-suh-dhaa-raa",
    r"\bMalayagiri\b": "Muh-luh-yuh-gih-ree",
    r"\bKhandagiri\b": "Khun-duh-gih-ree",
    r"\bBarehipani\b": "Buh-ray-hee-puh-nee",
    r"\bKhandadhar\b": "Khun-duh-dhaar",
    r"\bBadaghagra\b": "Buh-duh-ghaag-raa",
    r"\bSanaghagra\b": "Saa-nuh-ghaag-raa",
    r"\bPuri\ Beach\b": "Poo-ree Beach",
    r"\bDaringbadi\b": "Daa-ring-baa-dee",
    r"\bHinjilicut\b": "Hin-jih-lee-kut",
    r"\bChhatrapur\b": "Chhuh-truh-poor",
    r"\bDharmagarh\b": "Dhur-muh-gud",
    r"\bTitilagarh\b": "Tee-tih-laa-gud",
    r"\bKantabanji\b": "Kun-tuh-bun-jee",
    r"\bRajgangpur\b": "Raaj-gung-poor",
    r"\bKankadahad\b": "Kuhn-kuh-duh-hud",
    r"\bKhandapada\b": "Khun-duh-puh-daa",
    r"\bBrahmagiri\b": "Bruh-muh-gih-ree",
    r"\bBanki\ Town\b": "Bung-kee Town",
    r"\bBasudevpur\b": "Baa-soo-dev-poor",
    r"\bMadhu\ Babu\b": "Maa-dhoo Baa-boo",
    r"\bVyasa\ Kabi\b": "Vyaa-suh Kuh-bee",
    r"\bPadmashree\b": "Pud-muh-shree",
    r"\bDharmapada\b": "Dhur-muh-puh-duh",
    r"\bOdisha\ Day\b": "Oh-dee-shaa Day",
    r"\bBhima\ Bhoi\b": "Bhee-muh Boy",
    r"\bGopi\ Bhasa\b": "Goh-pee Bhaa-shaa",
    r"\bDadi\ Budha\b": "Daa-dee Boo-dhaa",
    r"\bBhaktakabi\b": "Bhuk-tuh-kuh-bee",
    r"\bChaturdasi\b": "Chuh-toor-duh-shee",
    r"\bAmrit\ Kaal\b": "Um-reet Kaal",
    r"\bDanadharma\b": "Daa-nuh-dhur-muh",
    r"\bSadhabapua\b": "Saa-dhuh-buh-poo-aa",
    r"\bOdia\ Bhasa\b": "Oh-dee-aa Bhaa-shaa",
    r"\bMatrubhasa\b": "Maa-troo-bhaa-shaa",
    r"\bMaa\ Chandi\b": "Maa Chun-dee",
    r"\bSri\ Biraja\b": "Sri Bih-ruh-jaa",
    r"\bSri\ Sarala\b": "Sri Saa-ruh-laa",
    r"\bSri\ Tarini\b": "Sri Taa-rih-nee",
    r"\bSri\ Chandi\b": "Sri Chun-dee",
    r"\bJagannath\b": "Jug-un-naath",
    r"\bSudarshan\b": "Soo-dur-shun",
    r"\bAlwarnath\b": "Aal-vaar-naath",
    r"\bCharchika\b": "Chur-chih-kaa",
    r"\bLingaraja\b": "Ling-guh-raaj",
    r"\bGupteswar\b": "Goop-tesh-wurr",
    r"\bMukteswar\b": "Mook-tesh-wurr",
    r"\bMegheswar\b": "May-ghesh-wurr",
    r"\bSureswari\b": "Soo-resh-wuh-ree",
    r"\bMahalaxmi\b": "Maa-haa-lux-mee",
    r"\bRadharani\b": "Raa-dhaa-raa-nee",
    r"\bIsaneswar\b": "Ee-shuh-nesh-wurr",
    r"\bUgra\ Tara\b": "Oog-ruh Taa-raa",
    r"\bBhagabati\b": "Bhaa-guh-buh-tee",
    r"\bDhumavati\b": "Dhoo-muh-vuh-tee",
    r"\bTara\ Devi\b": "Taa-raa Day-vee",
    r"\bThakurani\b": "Thaa-koo-raa-nee",
    r"\bBudhi\ Maa\b": "Boo-dhee Maa",
    r"\bMaheswari\b": "Maa-hesh-wuh-ree",
    r"\bVaishnavi\b": "Vye-shnuh-vee",
    r"\bNarasimhi\b": "Nuh-ruh-sing-hee",
    r"\bPujapanda\b": "Poo-jaa-pun-daa",
    r"\bDaitapati\b": "Dye-tuh-puh-tee",
    r"\bMahasuara\b": "Muh-haa-soo-aar",
    r"\bPratihari\b": "Pruh-tee-haa-ree",
    r"\bMudirasta\b": "Moo-dee-rus-tuh",
    r"\bRajavesha\b": "Raa-jaa-vay-shuh",
    r"\bJagamohan\b": "Juh-guh-moh-hun",
    r"\bRatnavedi\b": "Rut-nuh-vay-dee",
    r"\bRosaghara\b": "Roh-suh-ghuh-ruh",
    r"\bAnavasara\b": "Uh-nuh-buh-suh-ruh",
    r"\bHabisiali\b": "Huh-bee-see-yaa-lee",
    r"\bSesa\ Raja\b": "Say-suh Ruh-joh",
    r"\bKali\ Puja\b": "Kaa-lee Poo-jaa",
    r"\bDeepavali\b": "Dee-paa-vuh-lee",
    r"\bBada\ Osha\b": "Buh-duh Oh-shaa",
    r"\bUda\ Parba\b": "Oo-daa Pur-buh",
    r"\bPus\ Punei\b": "Poosh Poo-nyee",
    r"\bGhee\ Anna\b": "Ghee Un-nuh",
    r"\bOuu\ Dalma\b": "Oh-oo Duhl-maa",
    r"\bDahi\ Bara\b": "Duh-hee Buh-raa",
    r"\bBela\ Pana\b": "Bay-luh Puh-naa",
    r"\bMuga\ Dali\b": "Moo-guh Daa-lee",
    r"\bButa\ Dali\b": "Boo-tuh Daa-lee",
    r"\bDaskathia\b": "Dush-kuh-thee-aa",
    r"\bPasapalli\b": "Paa-saa-pul-lee",
    r"\bHabaspuri\b": "Huh-bus-poo-ree",
    r"\bTribhanga\b": "Tree-bhung-guh",
    r"\bPadabheda\b": "Puh-duh-bhay-duh",
    r"\bOlasingha\b": "Oh-laa-sing-haa",
    r"\bSambalpur\b": "Sum-buhl-poor",
    r"\bBerhampur\b": "Behr-hum-poor",
    r"\bBrahmapur\b": "Bruh-muh-poor",
    r"\bKalahandi\b": "Kaa-laa-hun-dee",
    r"\bKendujhar\b": "Ken-doo-jhur",
    r"\bDhenkanal\b": "Dhen-kaa-naal",
    r"\bKandhamal\b": "Kun-dhuh-maal",
    r"\bBaitarani\b": "Bye-tuh-ruh-nee",
    r"\bTel\ River\b": "Tayl River",
    r"\bNiyamgiri\b": "Nee-yuhm-gih-ree",
    r"\bSimilipal\b": "Sih-mih-lee-paal",
    r"\bUdayagiri\b": "Oo-duh-yuh-gih-ree",
    r"\bRatnagiri\b": "Rut-nuh-gih-ree",
    r"\bLalitgiri\b": "Luh-lih-tuh-gih-ree",
    r"\bKolab\ Dam\b": "Koh-laab Dam",
    r"\bTikarpada\b": "Tee-kur-puh-daa",
    r"\bChandipur\b": "Chun-dee-poor",
    r"\bAryapalli\b": "Aar-yuh-pul-lee",
    r"\bAstaranga\b": "Uhs-tuh-rung-guh",
    r"\bDamanjodi\b": "Daa-mun-joh-dee",
    r"\bAnandapur\b": "Aa-nun-duh-poor",
    r"\bKhalikote\b": "Khaa-lee-koht",
    r"\bBalliguda\b": "Buhl-lee-goo-daa",
    r"\bPatnagarh\b": "Put-nuh-gud",
    r"\bJharbandh\b": "Jhaar-bun-dh",
    r"\bBonaigarh\b": "Boh-nye-gud",
    r"\bTileibani\b": "Tee-lay-ee-baa-nee",
    r"\bPallahara\b": "Puhl-luh-huh-raa",
    r"\bAthmallik\b": "Uht-muhl-lick",
    r"\bSatyabadi\b": "Sut-yuh-baa-dee",
    r"\bKantapada\b": "Kun-tuh-puh-daa",
    r"\bMarsaghai\b": "Mur-suh-ghye",
    r"\bRajkanika\b": "Raaj-kuh-nih-kaa",
    r"\bChandbali\b": "Chund-baa-lee",
    r"\bDhamnagar\b": "Dhum-nuh-gur",
    r"\bCharuvaki\b": "Chaa-roo-vah-kee",
    r"\bKharavela\b": "Khaa-ruh-vay-luh",
    r"\bSomavamsi\b": "Soh-muh-vum-shee",
    r"\bBaji\ Rout\b": "Baa-jee Rowt",
    r"\bUtkalmani\b": "Oot-kuhl-muh-nee",
    r"\bRama\ Devi\b": "Raa-maa Day-vee",
    r"\bManoj\ Das\b": "Muh-nohj Daas",
    r"\bBhagavata\b": "Bhaa-guh-vuh-tuh",
    r"\bHarivamsa\b": "Huh-ree-vum-shuh",
    r"\bKavisurya\b": "Kuh-vih-soor-yuh",
    r"\bTapaswini\b": "Tuh-pus-wih-nee",
    r"\bChautisha\b": "Chow-tee-shaa",
    r"\bSunyabada\b": "Shoon-yuh-baa-duh",
    r"\bMargasira\b": "Maar-guh-shee-ruh",
    r"\bSankranti\b": "Sung-kraan-tee",
    r"\bPratipada\b": "Pruh-tih-puh-daa",
    r"\bChaturthi\b": "Chuh-toor-thee",
    r"\bTrayodasi\b": "Truh-yoh-duh-shee",
    r"\bNakshatra\b": "Nuk-shuh-truh",
    r"\bRahu\ Kaal\b": "Raa-hoo Kaal",
    r"\bBudhabara\b": "Boo-dhuh-baa-ruh",
    r"\bSukrabara\b": "Shook-ruh-baa-ruh",
    r"\bDandabata\b": "Dun-duh-vut",
    r"\bDhanyabad\b": "Dhun-yuh-baad",
    r"\bBada\ Bapa\b": "Buh-duh Baa-paa",
    r"\bSana\ Bapa\b": "Saa-nuh Baa-paa",
    r"\bJeje\ Bapa\b": "Jay-jay Baa-paa",
    r"\bDedhasura\b": "Day-dhuh-soo-ruh",
    r"\bSanskruti\b": "Sun-skroo-tee",
    r"\bParampara\b": "Puh-rum-puh-raa",
    r"\bChasi\ Pua\b": "Chaa-see Poo-aa",
    r"\bBalarama\b": "Buhl-uh-raam",
    r"\bSubhadra\b": "Soo-bhuh-dhrah",
    r"\bGopinath\b": "Goh-pee-naath",
    r"\bAlarnath\b": "Aal-vaar-naath",
    r"\bKapilash\b": "Kuh-pee-laash",
    r"\bLokanath\b": "Loh-kuh-naath",
    r"\bLingaraj\b": "Ling-guh-raaj",
    r"\bRajarani\b": "Raa-jaa-raa-nee",
    r"\bYameswar\b": "Yuh-mesh-wurr",
    r"\bTaleswar\b": "Tuh-lesh-wurr",
    r"\bLadubaba\b": "Luh-doo-baa-baa",
    r"\bDamodara\b": "Daa-moh-duh-ruh",
    r"\bSridhara\b": "Shree-dhuh-ruh",
    r"\bBhairavi\b": "Bhy-ruh-vee",
    r"\bPitabali\b": "Pee-tuh-buh-lee",
    r"\bMetakani\b": "May-tuh-kuh-nee",
    r"\bChamunda\b": "Chaa-moon-daa",
    r"\bGajapati\b": "Guh-juh-puh-tee",
    r"\bMaharana\b": "Muh-haa-raa-naa",
    r"\bRupakara\b": "Roo-puh-kaa-ruh",
    r"\bGarabadu\b": "Guh-ruh-buh-doo",
    r"\bAbakasha\b": "Uh-buh-kaa-shuh",
    r"\bChhatisa\b": "Chhuh-tee-saa",
    r"\bGurubara\b": "Goo-roo-baa-ruh",
    r"\bDussehra\b": "Doo-say-hraa",
    r"\bDipavali\b": "Dee-paa-vuh-lee",
    r"\bPanchuka\b": "Pun-choo-kuh",
    r"\bNirmalya\b": "Neer-mahl-yuh",
    r"\bKaibalya\b": "Kye-buhl-yuh",
    r"\bKhechudi\b": "Khay-chuh-dee",
    r"\bPoi\ Saga\b": "Poy Saa-guh",
    r"\bRasagola\b": "Ruh-suh-goh-laa",
    r"\bRasabali\b": "Ruh-suh-buh-lee",
    r"\bAlu\ Chop\b": "Aa-loo Chop",
    r"\bKhanjani\b": "Khun-juh-nee",
    r"\bTarakasi\b": "Taa-raa-kuh-see",
    r"\bSand\ Art\b": "Sand Aart",
    r"\bSaktapar\b": "Shuk-tuh-paar",
    r"\bAbhinaya\b": "Uh-bhee-nuh-yuh",
    r"\bNuapatna\b": "Noo-aa-put-naa",
    r"\bBaripada\b": "Baa-ree-puh-daa",
    r"\bBalasore\b": "Buhl-uh-sohr",
    r"\bBaleswar\b": "Buhl-esh-wurr",
    r"\bRayagada\b": "Rye-uh-guh-daa",
    r"\bBalangir\b": "Buhl-uhn-geer",
    r"\bBolangir\b": "Buhl-uhn-geer",
    r"\bRourkela\b": "Rowr-keh-laa",
    r"\bDebagarh\b": "Day-buh-gud",
    r"\bKeonjhar\b": "Kee-yohn-jhur",
    r"\bNayagarh\b": "Nye-uh-gud",
    r"\bPhulbani\b": "Fool-baa-nee",
    r"\bNalabana\b": "Nuh-luh-buh-nuh",
    r"\bSatapada\b": "Suh-tuh-puh-daa",
    r"\bMahanadi\b": "Maa-haa-nuh-dee",
    r"\bBrahmani\b": "Bruh-muh-nee",
    r"\bIb\ River\b": "Ibb River",
    r"\bNagavali\b": "Naa-gaa-vuh-lee",
    r"\bBarabati\b": "Baa-ruh-baa-tee",
    r"\bRaibania\b": "Rye-baa-nee-aa",
    r"\bPotagarh\b": "Poh-tuh-gud",
    r"\bSatkosia\b": "Sut-koh-see-aa",
    r"\bGopalpur\b": "Goh-paal-poor",
    r"\bSunabeda\b": "Soo-naa-bay-daa",
    r"\bPolasara\b": "Poh-luh-suh-raa",
    r"\bBaliguda\b": "Baa-lee-goo-daa",
    r"\bUmerkote\b": "Oo-mur-koht",
    r"\bJunagarh\b": "Joo-naa-gud",
    r"\bSinapali\b": "Sih-nuh-puh-lee",
    r"\bAttabira\b": "Uht-tuh-bee-raa",
    r"\bPadampur\b": "Puh-dum-poor",
    r"\bGaisilet\b": "Gye-sih-let",
    r"\bBelpahar\b": "Bayl-puh-haar",
    r"\bKolabira\b": "Koh-laa-bee-raa",
    r"\bBanarpal\b": "Buh-nur-paal",
    r"\bParjanga\b": "Pur-jung-gaa",
    r"\bDaspalla\b": "Dush-pul-laa",
    r"\bSarankul\b": "Suh-run-kool",
    r"\bBalugaon\b": "Buhl-oo-gaanw",
    r"\bBolagarh\b": "Boh-laa-gud",
    r"\bNimapara\b": "Nee-muh-puh-daa",
    r"\bAstarang\b": "Uhs-tuh-rung",
    r"\bChoudwar\b": "Chow-dwaar",
    r"\bAthagarh\b": "Uht-tuh-gud",
    r"\bRajnagar\b": "Raaj-nuh-gur",
    r"\bGaradpur\b": "Guh-rud-poor",
    r"\bBalikuda\b": "Baa-lee-koo-daa",
    r"\bParadeep\b": "Puh-ruh-deep",
    r"\bBahanaga\b": "Baa-huh-nuh-gaa",
    r"\bJaleswar\b": "Juh-lesh-wurr",
    r"\bBaliapal\b": "Baa-lee-aa-paal",
    r"\bKaruwaki\b": "Kah-roo-vah-kee",
    r"\bJayadeva\b": "Juh-yuh-dhev",
    r"\bAstapadi\b": "Ush-tuh-puh-dee",
    r"\bBanamali\b": "Buh-nuh-maa-lee",
    r"\bSalabega\b": "Suh-luh-bay-guh",
    r"\bLachhama\b": "Luh-chhuh-maa",
    r"\bChaupadi\b": "Chow-puh-dee",
    r"\bBaramasi\b": "Baa-ruh-maa-see",
    r"\bMalasree\b": "Maa-luh-shree",
    r"\bBaisakha\b": "Bye-saa-khuh",
    r"\bJyeshtha\b": "Jyesh-thuh",
    r"\bShravana\b": "Shraa-buh-nuh",
    r"\bBhadraba\b": "Bhaa-dhruh-buh",
    r"\bPhalguna\b": "Phaal-goo-nuh",
    r"\bRuturaaj\b": "Roo-too-raaj",
    r"\bAmavasya\b": "Uh-maa-vus-yaa",
    r"\bPanchami\b": "Pun-chuh-mee",
    r"\bRavibara\b": "Ruh-vee-baa-ruh",
    r"\bSomabara\b": "Soh-muh-baa-ruh",
    r"\bSanibara\b": "Shuh-nee-baa-ruh",
    r"\bNamaskar\b": "Nuh-mus-kaar",
    r"\bMarigalu\b": "Muh-ree-guh-loo",
    r"\bBapa\-Maa\b": "Baa-paa Maa",
    r"\bBada\ Maa\b": "Buh-duh Maa",
    r"\bSana\ Maa\b": "Saa-nuh Maa",
    r"\bJeje\ Maa\b": "Jay-jay Maa",
    r"\bChandana\b": "Chun-duh-nuh",
    r"\bShraddha\b": "Shraadh",
    r"\bBhikshya\b": "Bheek-shyaa",
    r"\bBalaram\b": "Buhl-uh-raam",
    r"\bMadhava\b": "Maadh-uh-vuh",
    r"\bSamalei\b": "Suh-muh-lye",
    r"\bMangala\b": "Mung-guh-laa",
    r"\bHingula\b": "Hing-goo-laa",
    r"\bKapilas\b": "Kuh-pee-laas",
    r"\bMarichi\b": "Muh-ree-chee",
    r"\bKalijai\b": "Kaa-lee-jye",
    r"\bGovinda\b": "Goh-vin-duh",
    r"\bKeshava\b": "Kay-shuh-vuh",
    r"\bMatangi\b": "Maa-tung-gee",
    r"\bKaumari\b": "Kow-maa-ree",
    r"\bIndrani\b": "In-draa-nee",
    r"\bPahandi\b": "Puh-hun-dee",
    r"\bKhuntia\b": "Khoon-tee-aa",
    r"\bAmalaka\b": "Aam-luh-kuh",
    r"\bKhapuri\b": "Khaa-poo-ree",
    r"\bHaribol\b": "Huh-ree-bohl",
    r"\bHulhuli\b": "Hool-hoo-lee",
    r"\bAnasara\b": "Uh-nuh-suh-ruh",
    r"\bNuakhai\b": "Noo-aa-khye",
    r"\bPuspuni\b": "Poosh-poo-nee",
    r"\bSantula\b": "Sun-too-laa",
    r"\bKankada\b": "Kuhn-kuh-daa",
    r"\bPakhala\b": "Puh-khaa-luh",
    r"\bGhuguni\b": "Ghoo-ghoo-nee",
    r"\bAdrakha\b": "Uhd-ruh-khuh",
    r"\bBaigana\b": "Bye-guh-nuh",
    r"\bGotipua\b": "Goh-tee-poo-aa",
    r"\bGhumura\b": "Ghoo-moo-raa",
    r"\bMardala\b": "Mur-duh-luh",
    r"\bKendara\b": "Ken-duh-raa",
    r"\bChandua\b": "Chun-doo-aa",
    r"\bKansari\b": "Kaan-suh-ree",
    r"\bKaincha\b": "Kye-n-chuh",
    r"\bKhandua\b": "Khun-doo-aa",
    r"\bSonpuri\b": "Sohn-poo-ree",
    r"\bPallavi\b": "Pul-luh-vee",
    r"\bKalinga\b": "Kuh-ling-guh",
    r"\bToshali\b": "Toh-shuh-lee",
    r"\bKangoda\b": "Kung-goh-duh",
    r"\bKongoda\b": "Kohng-goh-duh",
    r"\bCuttack\b": "Kuh-tuck",
    r"\bKonarka\b": "Koh-naark",
    r"\bKhordha\b": "Khoor-dhaa",
    r"\bBhadrak\b": "Bhud-ruck",
    r"\bKoraput\b": "Koh-rah-poot",
    r"\bNuapada\b": "Noo-aa-puh-daa",
    r"\bSonepur\b": "Sohn-poor",
    r"\bBargarh\b": "Bur-gud",
    r"\bDeogarh\b": "Dev-gud",
    r"\bChilika\b": "Chih-lih-kaa",
    r"\bSalandi\b": "Suh-lun-dee",
    r"\bDeomali\b": "Day-oh-maa-lee",
    r"\bHirakud\b": "Hee-raa-kood",
    r"\bTalsari\b": "Taal-saa-ree",
    r"\bJeypore\b": "Jye-poor",
    r"\bChampua\b": "Chum-poo-aa",
    r"\bKesinga\b": "Kay-sing-gaa",
    r"\bKhariar\b": "Khuh-ree-aar",
    r"\bTushura\b": "Too-shoo-raa",
    r"\bUllunda\b": "Ool-loon-daa",
    r"\bPaikmal\b": "Pye-kuh-maal",
    r"\bLaikera\b": "Lye-kay-raa",
    r"\bBarkote\b": "Bur-koht",
    r"\bTalcher\b": "Taal-chayr",
    r"\bOdapada\b": "Oh-duh-puh-daa",
    r"\bNuagaon\b": "Noo-aa-gaanw",
    r"\bOdagaon\b": "Oh-duh-gaanw",
    r"\bBanapur\b": "Baan-poor",
    r"\bBegunia\b": "Bay-goo-nee-aa",
    r"\bDelanga\b": "Day-lung-gaa",
    r"\bSalepur\b": "Saa-lay-poor",
    r"\bTigiria\b": "Tee-gih-ree-aa",
    r"\bBaramba\b": "Buh-rum-baa",
    r"\bBadamba\b": "Buh-dum-baa",
    r"\bMahanga\b": "Muh-hung-gaa",
    r"\bDerabis\b": "Day-raa-bees",
    r"\bErasama\b": "Ay-ruh-suh-maa",
    r"\bNaugaon\b": "Now-gaanw",
    r"\bParadip\b": "Puh-ruh-deep",
    r"\bSimulia\b": "Sih-moo-lee-aa",
    r"\bNilgiri\b": "Neel-gih-ree",
    r"\bBhograi\b": "Bhohg-rye",
    r"\bAtibadi\b": "Uh-tih-buh-dee",
    r"\bChhanda\b": "Chhun-duh",
    r"\bBhajana\b": "Bhuh-juh-nuh",
    r"\bKirtana\b": "Keer-tuh-nuh",
    r"\bAshadha\b": "Aa-shaa-dhuh",
    r"\bSrabana\b": "Shraa-buh-nuh",
    r"\bAshwina\b": "Aash-wih-nuh",
    r"\bKartika\b": "Kaar-tih-kuh",
    r"\bFalguna\b": "Phaal-goo-nuh",
    r"\bChaitra\b": "Chye-truh",
    r"\bHemanta\b": "Hay-mun-tuh",
    r"\bBasanta\b": "Buh-sun-tuh",
    r"\bPurnima\b": "Poor-nih-maa",
    r"\bDwitiya\b": "Dwee-tee-yaa",
    r"\bTritiya\b": "Tree-tee-yaa",
    r"\bSaptami\b": "Sup-tuh-mee",
    r"\bAshtami\b": "Ush-tuh-mee",
    r"\bEkadasi\b": "Ay-kaa-duh-shee",
    r"\bDwadasi\b": "Dwaa-duh-shee",
    r"\bPanjika\b": "Pun-jee-kaa",
    r"\bPranama\b": "Pruh-naam",
    r"\bBhaijan\b": "Bhye-jaan",
    r"\bNananda\b": "Nuh-nun-duh",
    r"\bSansara\b": "Sun-saa-ruh",
    r"\bSangata\b": "Sung-gaa-tuh",
    r"\bSindura\b": "Sin-doo-ruh",
    r"\bMokshya\b": "Mohk-shyuh",
    r"\bSraddha\b": "Shrud-dhaa",
    r"\bSadhava\b": "Saa-dhuh-vuh",
    r"\bSumatra\b": "Soo-maa-traa",
    r"\bDharama\b": "Dhuh-ruh-maa",
    r"\bKutumba\b": "Koo-toom-buh",
    r"\bBiraja\b": "Bih-ruh-jaa",
    r"\bSarala\b": "Saa-ruh-laa",
    r"\bTarini\b": "Taa-rih-nee",
    r"\bChandi\b": "Chun-dee",
    r"\bBimala\b": "Bih-muh-laa",
    r"\bVimala\b": "Bih-muh-laa",
    r"\bVarahi\b": "Vaa-raa-hee",
    r"\bBarahi\b": "Baa-raa-hee",
    r"\bVamana\b": "Vaa-muh-nuh",
    r"\bBasuli\b": "Baa-soo-lee",
    r"\bKamara\b": "Kuh-maa-ruh",
    r"\bNijoga\b": "Nih-joh-guh",
    r"\bMailam\b": "Mye-lum",
    r"\bPahuda\b": "Puh-hoo-duh",
    r"\bKalasa\b": "Kuh-luh-suh",
    r"\bDhwaja\b": "Dhwuh-jaa",
    r"\bHabisa\b": "Huh-bee-suh",
    r"\bEnduri\b": "En-doo-ree",
    r"\bDiwali\b": "Dee-waa-lee",
    r"\bJagara\b": "Jaa-guh-ruh",
    r"\bAbadha\b": "Uh-baa-dhaa",
    r"\bKanika\b": "Kuh-nih-kaa",
    r"\bBesara\b": "Bay-suh-ruh",
    r"\bTorani\b": "Toh-ruh-nee",
    r"\bMalpua\b": "Maal-poo-aa",
    r"\bGuguni\b": "Ghoo-ghoo-nee",
    r"\bDhania\b": "Dhuh-nee-aa",
    r"\bSorisa\b": "Soh-ree-suh",
    r"\bHaladi\b": "Huh-luh-dee",
    r"\bChhena\b": "Chhay-naa",
    r"\bChaula\b": "Chow-luh",
    r"\bHarida\b": "Huh-ree-daa",
    r"\bBahada\b": "Buh-huh-daa",
    r"\bSukhua\b": "Soo-khoo-aa",
    r"\bChhatu\b": "Chhuch-too",
    r"\bPariba\b": "Puh-ree-baa",
    r"\bAmbula\b": "Aam-boo-luh",
    r"\bOdissi\b": "Oh-dih-see",
    r"\bMahari\b": "Maa-haa-ree",
    r"\bRanapa\b": "Ruh-nuh-paa",
    r"\bMahuri\b": "Maa-hoo-ree",
    r"\bKahali\b": "Kaa-haa-lee",
    r"\bGhanta\b": "Ghun-taa",
    r"\bNishan\b": "Nee-shaan",
    r"\bEktara\b": "Ayk-taa-raa",
    r"\bPipili\b": "Pee-pee-lee",
    r"\bDhokra\b": "Dohk-raa",
    r"\bBandha\b": "Bun-dhuh",
    r"\bBomkai\b": "Bohm-kye",
    r"\bChauka\b": "Chow-kaa",
    r"\bNritta\b": "Nrit-tuh",
    r"\bMudras\b": "Moo-dhrahs",
    r"\bHastha\b": "Hus-tuh",
    r"\bBhangi\b": "Bhung-gee",
    r"\bMoksha\b": "Mohk-shuh",
    r"\bUtkala\b": "Oot-kuhl",
    r"\bKosala\b": "Koh-suh-luh",
    r"\bTosali\b": "Toh-shuh-lee",
    r"\bKataka\b": "Kuh-tuh-kuh",
    r"\bKonark\b": "Koh-naark",
    r"\bDhauli\b": "Dhow-lee",
    r"\bJajpur\b": "Jaaj-poor",
    r"\bKhurda\b": "Khoor-dhaa",
    r"\bGanjam\b": "Gun-jaam",
    r"\bAnugul\b": "Uh-noo-gool",
    r"\bPrachi\b": "Praa-chee",
    r"\bDuduma\b": "Doo-doo-muh",
    r"\bBhuban\b": "Bhoo-vun",
    r"\bSurada\b": "Soo-ruh-daa",
    r"\bKodala\b": "Koh-duh-laa",
    r"\bKotpad\b": "Koht-paad",
    r"\bTarbha\b": "Tur-bhaa",
    r"\bBhatli\b": "Bhut-lee",
    r"\bSohela\b": "Soh-hay-laa",
    r"\bReamal\b": "Ree-aa-maal",
    r"\bKaniha\b": "Kuh-nee-haa",
    r"\bGondia\b": "Gohn-dee-aa",
    r"\bHindol\b": "Hin-dohl",
    r"\bRanpur\b": "Run-poor",
    r"\bBiridi\b": "Bih-ree-dee",
    r"\bTirtol\b": "Teer-tohl",
    r"\bKujang\b": "Koo-jung",
    r"\bDhamra\b": "Dhum-raa",
    r"\bTihidi\b": "Tee-hee-dee",
    r"\bKhaira\b": "Khye-raa",
    r"\bOupada\b": "Oh-oo-puh-daa",
    r"\bRemuna\b": "Ray-moo-naa",
    r"\bAshoka\b": "Uh-shoh-kuh",
    r"\bMalika\b": "Maa-lih-kaa",
    r"\bRebati\b": "Ray-buh-tee",
    r"\bDarbar\b": "Dur-baar",
    r"\bChampu\b": "Chhum-poo",
    r"\bJanana\b": "Juh-nuh-nuh",
    r"\bParaja\b": "Puh-ruh-jaa",
    r"\bAsadha\b": "Aa-shaa-dhuh",
    r"\bBhadra\b": "Bhaa-dhruh",
    r"\bAswina\b": "Aash-wih-nuh",
    r"\bPausha\b": "Pow-shuh",
    r"\bPousha\b": "Pow-shuh",
    r"\bGrisma\b": "Greesh-muh",
    r"\bBarsha\b": "Bur-shaa",
    r"\bSarata\b": "Shuh-ruh-tuh",
    r"\bSisira\b": "Shih-shih-ruh",
    r"\bSasthi\b": "Sush-thee",
    r"\bNavami\b": "Nuh-vuh-mee",
    r"\bDasami\b": "Dush-mee",
    r"\bPranam\b": "Pruh-naam",
    r"\bKahiki\b": "Kaa-hee-kee",
    r"\bKipari\b": "Kee-puh-ree",
    r"\bBhaini\b": "Bhye-nee",
    r"\bNatuni\b": "Naa-too-nee",
    r"\bDevara\b": "Day-vuh-ruh",
    r"\bSasura\b": "Suh-soo-ruh",
    r"\bBandhu\b": "Bun-dhoo",
    r"\bMitata\b": "Mee-taa-tuh",
    r"\bMelana\b": "May-luh-nuh",
    r"\bSankha\b": "Shung-khuh",
    r"\bPrasad\b": "Pruh-saadh",
    r"\bTarpan\b": "Tur-pun",
    r"\bBhakti\b": "Bhuk-tee",
    r"\bBorneo\b": "Borneo",
    r"\bBhauni\b": "Bhow-nee",
    r"\bAtithi\b": "Uh-tee-thee",
    r"\bSamaja\b": "Suh-maa-juh",
    r"\bAithya\b": "Eye-tee-hyuh",
    r"\bTahia\b": "Taa-hee-yaa",
    r"\bRatha\b": "Ruh-thuh",
    r"\bMekap\b": "May-kup",
    r"\bLenka\b": "Len-kaa",
    r"\bPaika\b": "Pye-kuh",
    r"\bDeula\b": "Day-oo-luh",
    r"\bKudua\b": "Koo-doo-aa",
    r"\bMatha\b": "Muth",
    r"\bDalma\b": "Duhl-maa",
    r"\bMudhi\b": "Moo-dhee",
    r"\bKhaja\b": "Khaa-jaa",
    r"\bPheni\b": "Fay-nee",
    r"\bKanti\b": "Kuhn-tee",
    r"\bPiaji\b": "Pee-yaa-jee",
    r"\bJeera\b": "Jee-raa",
    r"\bLanka\b": "Lung-kaa",
    r"\bNadia\b": "Nuh-dee-aa",
    r"\bChini\b": "Chee-nee",
    r"\bMaida\b": "Mye-daa",
    r"\bJanhi\b": "Jaahn-hee",
    r"\bChhau\b": "Chhow",
    r"\bDhola\b": "Dhoh-luh",
    r"\bTasha\b": "Taa-shaa",
    r"\bMadal\b": "Maa-duhl",
    r"\bBanam\b": "Baa-num",
    r"\bDokra\b": "Dohk-raa",
    r"\bNatya\b": "Naat-yuh",
    r"\bUtkal\b": "Oot-kuhl",
    r"\bAngul\b": "Uhn-gool",
    r"\bBoudh\b": "Bowdh",
    r"\bKomna\b": "Kohm-naa",
    r"\bBoden\b": "Boh-dun",
    r"\bBinka\b": "Bing-kaa",
    r"\bBonai\b": "Boh-nye",
    r"\bKoida\b": "Koy-daa",
    r"\bTensa\b": "Ten-saa",
    r"\bRasol\b": "Ruh-sohl",
    r"\bGania\b": "Guh-nee-aa",
    r"\bJatni\b": "Juht-nee",
    r"\bTangi\b": "Tung-gee",
    r"\bNiali\b": "Nee-aa-lee",
    r"\bBonth\b": "Bohnth",
    r"\bBasta\b": "Bus-taa",
    r"\bKoili\b": "Koy-lee",
    r"\bMagha\b": "Maa-ghuh",
    r"\bTithi\b": "Tee-thee",
    r"\bJuhar\b": "Joo-haar",
    r"\bAgyan\b": "Aag-gyaan",
    r"\bAgnya\b": "Aag-nyaa",
    r"\bHoita\b": "Hoy-tuh",
    r"\bKhudi\b": "Khoo-dee",
    r"\bMauza\b": "Mow-zaa",
    r"\bMausi\b": "Mow-see",
    r"\bJwain\b": "Jwaa-een",
    r"\bGhara\b": "Ghuh-ruh",
    r"\bGhata\b": "Ghaa-tuh",
    r"\bJatra\b": "Jaah-traa",
    r"\bBrata\b": "Bruh-tuh",
    r"\bArati\b": "Aa-ruh-tee",
    r"\bDhupa\b": "Dhoo-puh",
    r"\bBhoga\b": "Bhohg",
    r"\bPinda\b": "Pin-duh",
    r"\bPunya\b": "Poon-yuh",
    r"\bKarma\b": "Kur-muh",
    r"\bMukti\b": "Mook-tee",
    r"\bPrema\b": "Pray-muh",
    r"\bSneha\b": "Snay-huh",
    r"\bBoita\b": "Boy-tuh",
    r"\bSuar\b": "Soo-aar",
    r"\bOria\b": "Oh-ree-aa",
    r"\bBadi\b": "Buh-dee",
    r"\bGaja\b": "Guh-jaa",
    r"\bGhia\b": "Ghee-aa",
    r"\bKhua\b": "Khoo-aa",
    r"\bGuda\b": "Goo-duh",
    r"\bAtta\b": "Uht-taa",
    r"\bSuji\b": "Soo-jee",
    r"\bAnla\b": "Aam-laa",
    r"\bPala\b": "Paa-laa",
    r"\bTasa\b": "Taa-saa",
    r"\bGini\b": "Ghee-nee",
    r"\bIkat\b": "Ee-kut",
    r"\bOdra\b": "Oh-druh",
    r"\bPuri\b": "Poo-ree",
    r"\bDaya\b": "Duh-yaa",
    r"\bSoro\b": "Soh-roh",
    r"\bMamu\b": "Maa-moo",
    r"\bUsha\b": "Oo-shaa",
    r"\bKana\b": "Kuh-nuh",
    r"\bKete\b": "Kay-tay",
    r"\bBapa\b": "Baa-paa",
    r"\bBopa\b": "Boh-paa",
    r"\bBhai\b": "Bhye",
    r"\bNani\b": "Naa-nee",
    r"\bDidi\b": "Dee-dee",
    r"\bDada\b": "Daa-daa",
    r"\bPusa\b": "Poo-saa",
    r"\bPusi\b": "Poo-see",
    r"\bPita\b": "Pee-taa",
    r"\bMata\b": "Maa-taa",
    r"\bJhia\b": "Jhee-aa",
    r"\bNati\b": "Naa-tee",
    r"\bBohu\b": "Boh-hoo",
    r"\bSasu\b": "Saa-soo",
    r"\bGaon\b": "Gaanw",
    r"\bSahi\b": "Saa-hee",
    r"\bPara\b": "Puh-daa",
    r"\bHata\b": "Haa-tuh",
    r"\bOsha\b": "Oh-shaa",
    r"\bPuja\b": "Poo-jaa",
    r"\bDipa\b": "Dee-puh",
    r"\bPapa\b": "Paa-puh",
    r"\bJava\b": "Jaa-vaa",
    r"\bSeva\b": "Say-vaa",
    r"\bNiti\b": "Nee-tee",
    r"\bGop\b": "Gohp",
    r"\bAul\b": "Owl",
    r"\bKie\b": "Kee-ay",
    r"\bMaa\b": "Maa",
    r"\bApa\b": "Uh-paa",
    r"\bMai\b": "Mye",
    r"\bAja\b": "Aa-jaa",
    r"\bAai\b": "Aae",
    r"\bPua\b": "Poo-aa",
}

# Pre-compiled regex patterns for lightning-fast matching
COMPILED_LEXICON = [
    (re.compile(pattern, re.IGNORECASE), replacement)
    for pattern, replacement in ODIA_PHONETIC_LEXICON.items()
]


def clean_prose_for_tts(html_or_markdown: str) -> str:
    """
    Strips HTML tags, converts entities, removes raw markdown markers,
    and formats sentences cleanly for speech synthesis.
    """
    if not html_or_markdown:
        return ""

    # Decode HTML entities like &nbsp;, &amp;, &#39;
    text = unescape(html_or_markdown)

    # Remove code blocks entirely
    text = re.sub(r'```[\s\S]*?```', '', text)
    text = re.sub(r'`[^`]*`', '', text)

    # Strip HTML tags
    text = strip_tags(text)

    # Strip URLs
    text = re.sub(r'https?://\S+', '', text)

    # Clean markdown headers, bold, italics, blockquotes
    text = re.sub(r'^[#>]+\s*', '', text, flags=re.MULTILINE)
    text = re.sub(r'[*_~]', '', text)

    # Normalize whitespace
    text = re.sub(r'\s+', ' ', text).strip()
    return text


def apply_odia_phonetics(text: str) -> str:
    """
    Replaces Odia and cultural terms with phonetic spellings optimized
    for Indian English neural TTS voices.
    """
    if not text:
        return ""

    processed = text
    for regex, replacement in COMPILED_LEXICON:
        processed = regex.sub(replacement, processed)

    return processed


def prepare_dispatch_speech_text(title: str, author_name: str, prose_text: str) -> str:
    """
    Composes a complete, broadcast-quality spoken narrative of the dispatch:
    - Warm introductory cue
    - Natural narrative pacing with punctuation-based micro-pauses
    - Flawless Odia and Indic cultural phonetics
    """
    cleaned_prose = clean_prose_for_tts(prose_text)
    phonetic_prose = apply_odia_phonetics(cleaned_prose)

    clean_title = apply_odia_phonetics(clean_prose_for_tts(title))
    clean_author = apply_odia_phonetics(clean_prose_for_tts(author_name or "Karuwaki Editorial"))

    # Add acoustic introductory cue
    intro = f"Dispatch: {clean_title}. By {clean_author}."
    
    # Introduce deliberate narrative commas for pacing
    narrative_text = f"{intro} ... {phonetic_prose}"

    return narrative_text
