# Generated by Django 6.1.1 on 2026-09-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_excerpt_post_featured_post_reading_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ai_curated',
            field=models.BooleanField(default=False, help_text='Feature in AI Magazine showcase'),
        ),
        migrations.AddField(
            model_name='post',
            name='ai_mood',
            field=models.CharField(blank=True, choices=[('creative', 'Creative & Arts'), ('nostalgic', 'Nostalgic & Heritage'), ('learning', 'Deep Learning & Science'), ('fun', 'Fun & Lifestyle'), ('cosmic', 'Cosmic Wisdom')], default='creative', max_length=50),
        ),
    ]
