# Generated by Django 5.2.17 on 2026-09-04 14:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_blogcomment_edited_at_blogcomment_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full Name of the author', max_length=100)),
                ('slug', models.SlugField(help_text='Unique slug for author archive URL', max_length=120, unique=True)),
                ('avatar', models.ImageField(blank=True, help_text='Author avatar/portrait', null=True, upload_to='authors/')),
                ('designation', models.CharField(blank=True, default='', help_text='E.g., Senior Investigative Journalist, Archival Researcher', max_length=120)),
                ('bio', models.TextField(blank=True, default='', help_text='Short bio and background details')),
                ('x_handle', models.CharField(blank=True, default='', help_text='Twitter / X profile URL or @handle', max_length=100)),
                ('linkedin', models.URLField(blank=True, default='', help_text='LinkedIn profile URL')),
                ('website', models.URLField(blank=True, default='', help_text='Personal website or portfolio URL')),
                ('featured', models.BooleanField(default=False, help_text='Highlight as featured contributor')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(help_text='Legacy/Guest author name', max_length=40),
        ),
        migrations.AddField(
            model_name='post',
            name='author_profile',
            field=models.ForeignKey(blank=True, help_text='Linked curated author profile (overrides plain author text if set)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.author'),
        ),
    ]
