# Generated by Django 5.2.17 on 2026-09-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_author_alter_post_author_post_author_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio_content_hash',
            field=models.CharField(blank=True, help_text='SHA-256 of text when synthesized', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='audio_duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration in seconds'),
        ),
        migrations.AddField(
            model_name='post',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='dispatches/audio/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='post',
            name='audio_file_size',
            field=models.PositiveIntegerField(default=0, help_text='Size in bytes'),
        ),
        migrations.AddField(
            model_name='post',
            name='audio_status',
            field=models.CharField(choices=[('none', 'No Audio'), ('generating', 'Generating...'), ('ready', 'Ready'), ('stale', 'Content Updated (Stale)'), ('error', 'Generation Error')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='audio_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='audio_voice',
            field=models.CharField(default='en-IN-NeerjaExpressiveNeural', max_length=64),
        ),
    ]
