# Generated by Django 5.2.17 on 2026-09-07 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_audio_content_hash_post_audio_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preferred_audio_provider',
            field=models.CharField(choices=[('auto', 'Auto-Detect (Edge for EN/HI, Gemini for Odia)'), ('edge', 'Force Microsoft Edge-TTS (Free)'), ('gemini', 'Force Google Gemini AI Voice')], default='auto', help_text='Manual override for audio synthesis engine', max_length=20),
        ),
        migrations.CreateModel(
            name='DispatchAudioTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi (हिन्दी)'), ('or', 'Odia (ଓଡ଼ିଆ)')], default='en', max_length=10)),
                ('provider', models.CharField(choices=[('edge', 'Microsoft Edge Neural (Free)'), ('gemini', 'Google Gemini AI Voice')], default='edge', max_length=20)),
                ('voice_name', models.CharField(default='en-IN-NeerjaExpressiveNeural', max_length=64)),
                ('audio_file', models.FileField(upload_to='dispatches/audio/%Y/%m/')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in seconds')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Size in bytes')),
                ('content_hash', models.CharField(blank=True, help_text='SHA-256 of text when synthesized', max_length=64, null=True)),
                ('status', models.CharField(choices=[('none', 'No Audio'), ('generating', 'Generating...'), ('ready', 'Ready'), ('stale', 'Content Updated (Stale)'), ('failed', 'Generation Failed')], default='none', max_length=20)),
                ('is_primary', models.BooleanField(default=True, help_text='Active audio track for reader playback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_tracks', to='blog.post')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
                'indexes': [models.Index(fields=['post', 'is_primary'], name='blog_dispat_post_id_07a4c5_idx'), models.Index(fields=['language', 'provider'], name='blog_dispat_languag_c44461_idx')],
            },
        ),
    ]
