# Generated by Django 3.2.6 on 2021-09-14 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsImage',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('slideNo', models.IntegerField(default=0, unique=True)),
                ('image', models.ImageField(upload_to='News/2021-09-14/')),
                ('refUrl', models.CharField(blank=True, default='', max_length=130)),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PageViews',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('news', models.IntegerField(default=0)),
                ('podcast', models.IntegerField(default=0)),
            ],
        ),
    ]
