# Generated by Django 3.2.6 on 2021-09-14 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_newsimage_pageviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageviews',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
