# Generated by Django 3.2.6 on 2021-09-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_pageviews_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symphony_in_life',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('symphony_in_life', models.FileField(upload_to='symphony_in_life/%y')),
            ],
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(upload_to='News/2021-09-29/'),
        ),
    ]
