# Generated by Django 3.2.6 on 2021-10-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210929_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(upload_to='News/2021-10-02/'),
        ),
    ]
