# Generated by Django 3.2.6 on 2021-10-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_newsimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='symphony_in_life',
            name='thumb',
            field=models.FileField(blank=True, upload_to='thumb/%y'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(upload_to='News/2021-10-13/'),
        ),
    ]
