# Generated by Django 3.2.6 on 2022-08-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211013_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magical_world_of_books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('magical_world_of_books', models.FileField(upload_to='magical_world_of_books/%y')),
                ('thumb', models.FileField(blank=True, upload_to='thumb/%y')),
            ],
        ),
        migrations.DeleteModel(
            name='Symphony_in_life',
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(upload_to='News/2022-08-03/'),
        ),
    ]
