# Generated by Django 3.2.6 on 2022-12-01 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220803_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicalWorldOfBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=130)),
                ('caption', models.CharField(max_length=100)),
                ('magical_world_of_books', models.FileField(upload_to='magical_world_of_books/%y')),
                ('thumb', models.FileField(blank=True, upload_to='thumb/%y')),
                ('timeStamp', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(upload_to='News/2022-12-01/'),
        ),
    ]
