# Generated by Django 6.1.1 on 2026-09-03 09:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_newsimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athereal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date of cosmic alignment', unique=True)),
                ('tithi_title', models.CharField(default='AAJ KI TITHI', help_text='Title or Tithi Name (e.g., AAJ KI TITHI, Shukla Paksha Pratipada)', max_length=200)),
                ('location', models.CharField(default='India', max_length=150)),
                ('sunrise', models.CharField(default='5:23 a.m.', max_length=50)),
                ('sunset', models.CharField(default='5:48 p.m.', max_length=50)),
                ('moonrise', models.CharField(default='9:57 p.m.', max_length=100)),
                ('moonset', models.CharField(default='12:06 p.m.', max_length=100)),
                ('amrit_kaal', models.CharField(default='10:12 p.m. – 11:43 p.m.', max_length=100)),
                ('rahu_kaal', models.CharField(default='1:09 p.m. – 2:42 p.m.', max_length=100)),
                ('abhijit', models.CharField(default='11:11 a.m. – noon', max_length=100)),
                ('nakshatra', models.CharField(blank=True, default='', help_text='e.g. Rohini, Ashwini, etc.', max_length=100)),
                ('cosmic_insight', models.TextField(blank=True, default='', help_text='Daily AI Astrology guidance or ancient cosmic wisdom')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Athereal Astro Entry',
                'verbose_name_plural': 'Athereal Astro Entries',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='magical_world_of_books',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='magicalworldofbooks',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(upload_to='News/2026-09-03/'),
        ),
    ]
