# Generated by Django 5.2.17 on 2026-09-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post_reactions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(upload_to='News/2026-09-04/'),
        ),
    ]
