# Generated by Django 5.2.17 on 2026-09-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_profile_post_reactions_alter_newsimage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Magical_world_of_books',
        ),
    ]
