# Generated by Django 5.2.17 on 2026-09-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_delete_magical_world_of_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MagicalWorldOfBooks',
        ),
    ]
