# Generated by Django 5.2.17 on 2026-09-04 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_delete_magicalworldofbooks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newsImage',
        ),
        migrations.DeleteModel(
            name='PageViews',
        ),
    ]
