# Generated by Django 5.2.17 on 2026-09-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_delete_newsimage_delete_pageviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_comments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
